### ISSUE TITLE
Incoming Forces - rendering issues

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#100]
This will be an "interesting" game to fix, because it doesn't work with WineD3D. It works fine with d8vk as long as the virtual desktop is on in Wine, however the rendering is broken at times, with what I'd generally call "vertex surrealism". 

It can be clearly noticed when the first mission intro gets to the hangar in the attached trace. Apologies for the abrupt end in the trace, but at some point I simply couldn't bear the 1fps capture any more and it had gotten past the interesting point anyway (the cutscenes are unskippable...).

### Software information
Incoming Forces (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: f4988e7

### Apitrace file(s)
[forces.trace.tar.xz](https://drive.google.com/file/d/15ACWHE-bg8EYzNcfY_X7GYxopfIk-9Ha/view?usp=share_link)

### Log files
- d3d8.log: [forces_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10573407/forces_d3d8.log)
- d3d9.log: [forces_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10573409/forces_d3d9.log)

**Comment by Blisto91** [comment]
INCOMING!!! HIDE! :runner:

**Comment by AlpyneDreams** [comment]
Seems like this behaves the same way on WineD3D. Not sure what I can do to fix this, if anything.

**Comment by WinterSnowfall** [comment]
Just to note the "progress" here, moving VB/IB to MANAGED has made the problem even worse :smile: .

<details>

<summary>Spoiler</summary>

![Incoming](https://user-images.githubusercontent.com/6306593/233613085-b4390f53-227b-4cb6-b3ff-94c880ae9cb6.png)

</details>

**Comment by AlpyneDreams** [comment]
This game is doing very weird stuff with buffers. The soldier models that are broken are SYSTEMMEM DYNAMIC, but not WRITEONLY, vertex/index buffers that are being locked constantly with DISCARD and NOOVERWRITE, inconsistently.

This is the first offending draw call and the one before it, in frame 326 of the trace:
![image](https://user-images.githubusercontent.com/3376691/233766972-ea45a37c-ff10-474f-a364-3d6db048d91b.png)

It seem to have indices that refer to verts from outside the range that was locked before the drawcall so I assume this is an issue with the index buffer being trampled on, possibly by the next or previous draw call.

Also, it's probably reading back from the buffers and doing its own TCL on the CPU, I think. 

Vertices / indices come into the vertex shader already clipped, skinned, lit, and locally transformed.
![image](https://user-images.githubusercontent.com/3376691/233765250-c6ba2a4f-fd49-4821-85c1-8888b4acb982.png)

Occasionally, it gets it very wrong:
![image](https://user-images.githubusercontent.com/3376691/233765359-d9ad0a81-c8b9-4248-8337-a37d9c395e99.png)


If it's reading something back from the buffers that is wrong then it may be applying TCL to it wrong too. It might be difficult to debug this issue with just the apitrace, so I think this one will have to wait.

**Comment by WinterSnowfall** [comment]
I've tried forcing SWVP on the game and it seems to be fine with that:

> error Creating device (behaviour D3DCREATE_HARDWARE_VERTEXPROCESSING PUREDEVICE)
> error Creating device (behaviour D3DCREATE_HARDWARE_VERTEXPROCESSING)
> error Creating device (behaviour D3DCREATE_MIXED_VERTEXPROCESSING)
> found suitable behaviour D3DCREATE_SOFTWARE_VERTEXPROCESSING

... but sadly it doesn't help with the above. I've finished the game ages ago on a Riva TNT2 M64 (which had no HWVP IIRC), which is why I thought it was worth a shot.

I guess this might be SSE2 related after all, as noted above. Forcing the msvcp90.dll and msvcr90.dll the game ships with doesn't seem to fix anything though.

**Comment by WinterSnowfall** [comment]
> I guess this might be SSE2 related after all, as noted above. Forcing the msvcp90.dll and msvcr90.dll the game ships with doesn't seem to fix anything though.

Some updates on that front:
- I've tested the game with a variant of the msvcrt.dll from Wine that has SSE2 support disabled. That does nothing to fix the game, although the game does load it.
- To make it even more apparent that it's unrelated, WineD3D now renders the offending section correctly, namely the marines in the docking bay (tested with Wine 9.8).

**Comment by WinterSnowfall** [comment]
Looks fine now with dxvk master, not sure what fixed it, but I'm happy to put it behind us.
