### ISSUE TITLE
Port Royale 2 - crash when starting a new game

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#103]
The game crashes right after the loading screen, a couple of frames into rendering the starting city in a new game. It works just fine with WineD3D.

Tracing it with d3d8 apitrace caused it to outright crash, so the trace is captured with d3d8to9 and WineD3D.

There are some textures missing when playing back the trace with d8vk, so perhaps it's about some unsupported texture formats again?

To actually run the game in the first place, one must make sure to override some of the dlls the game ships:
`WINEDLLOVERRIDES="msvcr71,msvcp71,dbghelp=n" wine PR2.exe`

If you get an error saying "Could not find translation files" or something similar, that's just the game's way of saying "I have crashed because of reasons", it doesn't actually mean what it says.

P.S.: I also noticed WineD3D clears the background on the loading screen, when the hourglass is shown, while d8vk holds onto the last rendered background from the main menu. Perhaps this is something else to look into.

### Software information
Port Royale 2 (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: f4988e7

### Apitrace file(s)
[PR2.trace.tar.xz](https://drive.google.com/file/d/1XkR5VmvxUNYCd5_iAGKDOwGC_XqEP_pN/view?usp=share_link)

### Log files
- d3d8.log: [PR2_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10577693/PR2_d3d8.log)
- d3d9.log: [PR2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10577697/PR2_d3d9.log)

**Comment by WinterSnowfall** [comment]
No longer crashes as of 43f9208, however there's one minor thing. The loading screen background gets cleared with WineD3D, but not with d8vk (possibly a backbuffer surface is not cleared?)

![PRLoadingD8VK](https://user-images.githubusercontent.com/6306593/221124011-34dd24f9-6669-4768-9fea-2093f679e190.png)

![LoadingScreenWineD3D](https://user-images.githubusercontent.com/6306593/221124040-05bc36e1-4f94-4d88-b12b-1da27f0ed776.png)

**Comment by AlpyneDreams** [comment]
This is correct, see https://youtu.be/vBeJNxfpZ0g?t=89

**Comment by qinlili23333** [comment]
When I tried D8VK for this game on Windows,  something weird happened. 
The menu cannot render properly. I have recorded a video:https://youtu.be/NPS9Wo4t9Tg

I also tried d3d8to9 with DXVK9 and got the menu render properly.
RTX3060Laptop, 546.33 clean installed driver, Win11 22623.746
D8VK 1.0 from Release
(Latest build from Action tested, cannot launch with no message, the process directly exit without any log output)

I'm not sure whether it's windows bug or D8VK bug, but this may be helpful so I reply here.

**Comment by WinterSnowfall** [comment]
> When I tried D8VK for this game on Windows, something weird happened. The menu cannot render properly.

I sort of added a fix for this issue even on main, but it's not in 1.0 unfortunately. And current main sort of breaks some games due to device reset not being fully handled properly (I have an open PR for that as well).

Long story short, if you want to play the game with 1.0 (for the moment that's the recommended version to use) add a dxvk.conf file next to the game executable with `d3d8.managedBufferPlacement = False` in it.

I also have a PR disabling managedBufferPlacement altogether exactly because it causes these kind of issues and moreover tanks performance in some games. So the good news is that the problem should be universally fixed in the future (it affects other games as well, not only PR2).

**Comment by qinlili23333** [comment]
> Long story short, if you want to play the game with 1.0 (for the moment that's the recommended version to use) add a dxvk.conf file next to the game executable with `d3d8.managedBufferPlacement = False` in it.

Thanks, this works for me. I have updated [PCGamingWiki page](https://www.pcgamingwiki.com/wiki/Port_Royale_2#Game_does_not_start_or_stuck_in_blackscreen_without_responding) for this.

**Comment by WinterSnowfall** [comment]
> I have updated [PCGamingWiki page](https://www.pcgamingwiki.com/wiki/Port_Royale_2#Game_does_not_start_or_stuck_in_blackscreen_without_responding) for this.

While technically correct for now, the PCGW suggestion should just be a more generic "use d8vk". The `d3d8.managedBufferPlacement = False` part is technically a d8vk bug that will get fixed (actually **_it is_** already fixed on main). But I guess you can leave it as is for clarity and I'll make a note to edit it a bit once we release a new version or get merged upstream.

Also, you might want to raise an issue with GOG Support if their wrapper has issues on Intel hardware, since its entire stated purpose of existence is to increase compatibility on Windows systems.
