### ISSUE TITLE
Commandos 3 - graphical corruption

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#107]
Rendering appears broken while in game, whereas WineD3D works just fine.

![C3](https://user-images.githubusercontent.com/6306593/218568388-673fcc9c-c5af-427c-84e2-2d95b292810b.png)

### Software information
Commandos 3 (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: f4988e7

### Apitrace file(s)
[Commandos3.trace.tar.xz](https://drive.google.com/file/d/1PYdhHfjZmTxLF6xpuENcpzwEjVS_3Y41/view?usp=share_link)

### Log files
- d3d8.log: [Commandos3_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10726076/Commandos3_d3d8.log)
- d3d9.log: [Commandos3_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10726077/Commandos3_d3d9.log)

**Comment by AlpyneDreams** [comment]
Hmm, having trouble reproducing this one from the trace. Does the trace look like that or just the game?

![image](https://user-images.githubusercontent.com/3376691/220814859-65931231-f567-4fc0-a30f-d56296cf9347.png)

**Comment by AlpyneDreams** [comment]
Also, is this a WineD3D trace, or a d8vk trace? I am noticing unexpected object destruction on the backbuffer which is interesting.

**Comment by AlpyneDreams** [comment]
I have fixed backbuffers not being cached properly in 0edc684ebf4f0ddfa90cf1d4c3b242706045031a, which led to the unexpected object destruction. Let me know if this also fixes the bug.

**Comment by WinterSnowfall** [comment]
> Also, is this a WineD3D trace, or a d8vk trace? I am noticing unexpected object destruction on the backbuffer which is interesting.

It's a WineD3D trace. FWIW it crashes on replay with d8vk (at least on Nvidia), so I can't comment if it reproduces the issue or not.

Edit: Nevermind, I see you're on Nvidia as well.

> I have fixed backbuffers not being cached properly in [0edc684](https://github.com/AlpyneDreams/d8vk/commit/0edc684ebf4f0ddfa90cf1d4c3b242706045031a), which led to the unexpected object destruction. Let me know if this also fixes the bug.

Unfortunately it does not. The game still behaves and looks the same. I've done a [screen capture](https://drive.google.com/file/d/17mmH6t91nfSNdXos9Jz5lEqoJwF-A6Fu/view?usp=share_link), so it's more clear what the game looks like. I'm also getting consistent crashing on exit and occasional crashing on startup - none of which happens with WineD3D.

**Comment by WinterSnowfall** [comment]
With latest master (8ddf18f) it now crashes when starting a new game. The trace still plays back fine.

**Comment by WinterSnowfall** [comment]
bcad6a4 has definitely pushed things in the right direction (see below). There's no more crashing and the screen resolution is correct now, however there's still some vertex flickering caused by moving objects and mouse interactions.

![C3](https://user-images.githubusercontent.com/6306593/222949509-cd2170fa-01df-4564-b30e-30ab7f282aec.png)
