### ISSUE TITLE
Duke Nukem: Manhattan Project - problems with keyboard input

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [AlpyneDreams/d8vk#108]
While using d8vk, first of all game has to be limited to 60fps because otherwise the game has some issue with handling input and for example double jump doesn't work. Windows has same issue so its not dxvk d8vk or linux related but i'm leaving it here as it maybe might be. After limiting the fps via `DXVK_FRAME_RATE=60` the game runs fine but sometimes inputs are not registered. For example when i get jetpack often i can hold up for like 3 seconds and nothing is happening, often jump doesn't work etc. I tried limiting the fps in game but that only improved it marginally.

### System information
![Screenshot_20230215_203452](https://user-images.githubusercontent.com/11545014/219134115-89cbd585-35f0-4eb7-89dd-b915b9d1f339.png)
Wine: wine-8.0 (Staging)

### Log files
[prism3d_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10746720/prism3d_d3d9.log)

**Comment by WinterSnowfall** [comment]
I might have an idea about what's going on here... but first some questions :).

a) What refresh rate are you actually using?
b) Are you running the game windowed or fullscreen?

**Comment by Michal-Szczepaniak** [comment]
a) 60
b) windowed, i tried fullscreen in emulated desktop

**Comment by WinterSnowfall** [comment]
60 Hz? I was under the impression you were on a high refresh rate monitor... I can run it at 75Hz on mine and haven't noticed any problems.

In any case, something you can try is grabbing the dxvk.conf file from the repo and using:
```
d3d9.maxFrameRate = 60
d3d9.presentInterval = 0
```
That will limit the framerate to 60 and disable Vsync (which the game forces on). I've had times when the frame limiter was not working properly when Vsync was also enabled, so it's worth a try.

**Comment by Michal-Szczepaniak** [comment]
I'm happy to announce that I can't tell difference now between d8vk/opengl/wined3d, that was it, and also fixes a lot of microstutters. Thanks for help!

**Comment by WinterSnowfall** [comment]
Happy to hear it helped :). I don't really need any such tricks here on Nvidia, but then again I've seen fame-limiting issues manifest differently on various setups so I'm not too surprised...

**Comment by Michal-Szczepaniak** [comment]
partially it was issue with my keyboard lmao
