### ISSUE TITLE
Nice to have wiki additions

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#119]
We should probably clarify a bit what "Supported games" means, to allow less speculation, namely:
- The games will work fine from a d3d standpoint, but may still need various workarounds/winetricks/protontricks to work properly in Wine/Proton
- Peformance on Intel iGPUs may at times be a lot worse than with WineD3D and its OpenGL backend (this is a problem we've inherited from dxvk and not something we can address; at best maybe ANV advancements in mesa may improve things in the future)
- A Windows disclaimer similar to what dxvk has would be nice, as I don't think we'll be doing extensive testing on Windows, but I'm sure some people will end up using d8vk there as well (in any case, Windows support seems to have improved since b3fb153)

Also, I think installation instructions should have their own section, separate from building & debugging.

**Comment by mrdeathjr28** [comment]
> * Peformance on Intel iGPUs may at times be a lot worse than with WineD3D and its OpenGL backend (this is a problem we've inherited from dxvk and not something we can address; at best maybe ANV advancements in mesa may improve things in the future)

This dont completly correct maybe some time ago but now is completly different, especially for hardware before Xe (Xe actually stay affected with many issues related to dev like xe kernel and this need time for show improvements)

In my case runs very well and with less problems compared nvidia gtx 1050 (stutter, compatibility and other things) however needs lastest mesa like oibaf ppa and high frecuency memory in my case 3600mhz

And as personal experience recommend have rebar, in my case give a better performance for example:

no-rebar

![norebar](https://user-images.githubusercontent.com/6601480/224574340-28788bde-c069-4a30-9444-b77a2da99198.png)

rebar

![rebar](https://user-images.githubusercontent.com/6601480/224574349-412c674f-320b-4395-bb28-5087f75f339f.png)

**Comment by WinterSnowfall** [comment]
> In my case runs very well and with less problems compared nvidia gtx 1050 (stutter, compatibility and other things) however needs lastest mesa like oibaf ppa and high frecuency memory in my case 3600mhz

That is good to hear. Still, I have an Intel Xe powered laptop (TGL GT2) running latest mesa (git) with 4600 MT/s memory and get abysmal performance in some cases compared to WineD3D (albeit it only seems to happen in some games, but the same games on Nvidia run better than with WineD3D). Laptop/mobile iGPUs seem more impacted in these scenarios, which is why I've said "at times", however this is a known problem and we should include a note for it as such.

**Comment by mrdeathjr28** [comment]
> > In my case runs very well and with less problems compared nvidia gtx 1050 (stutter, compatibility and other things) however needs lastest mesa like oibaf ppa and high frecuency memory in my case 3600mhz
> 
> That is good to hear. Still, I have an Intel Xe powered laptop (TGL GT2) running latest mesa (git) with 4600 MT/s memory and get abysmal performance in some cases compared to WineD3D (albeit it only seems to happen in some games, but the same games on Nvidia run better than with WineD3D). Laptop/mobile iGPUs seem more impacted in these scenarios, which is why I've said "at times", however this is a known problem and we should include a note for it as such.

In my case almost buy Arc A380 but when intel announce new kernel for Xe, i choose wait because this is big change and need time to stay mature

And yeah laptop mobile parts are very diferent compared desktop and in your case is Xe based, Xe must be good once stay mature drivers (i hope this can happpen around in 1 or 2 years)
