### ISSUE TITLE
Can you please release x86 Windows DLL's

### ISSUE THREAD

**Issue by ufukbakan** [AlpyneDreams/d8vk#12]
I am not able to build this project can you please release a version of x86 dlls.

**Comment by AlpyneDreams** [comment]
They are already released here:
https://github.com/AlpyneDreams/d8vk/releases/tag/v0.1.0

New update will probably come soon.

**Comment by AlpyneDreams** [comment]
If you have any further issues building on Windows open a new issue with more information, like logs.
