### ISSUE TITLE
Pure Pinball 2.0 Redux - untextured pinball

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#129]
The texture on the pinball seems to be missing - as it is just a pitch black sphere. I would have liked to compare it against WineD3D, however the game crashes if I try to do that (perhaps we have another d8vk exclusive on our hands).

![Black](https://user-images.githubusercontent.com/6306593/228656518-9f3ce355-89fb-411e-98bc-32a6b215d302.png)

The attached trace was captured with d8vk, but I'm hoping it's enough. Maybe it's an obscure texture format that's missing.

### Software information
Pure Pinball 2.0 Redux (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.85.05
- Wine version: 8.4 Staging
- DXVK version: 2c56a1a

### Apitrace file(s)
[Pure Pinball 2.0 REDUX.trace.tar.xz](https://drive.google.com/file/d/18jSj3AaA4q3W4oiKk7VkCODIqq8LJdWe/view?usp=share_link)

### Log files
- d3d8.log: [Pure Pinball 2.0 REDUX_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11105118/Pure.Pinball.2.0.REDUX_d3d8.log)

**Comment by dungeon007** [comment]
Probably not an exclusive... it does not run on AMD. Same as MCO that does not run on AMD.
I guess drivers keeps asserting if there are some "wrong" things around, thus not allowing such things to run :dagger:  
And WINED3D probably just do the same.

**Comment by AlpyneDreams** [comment]
A little more than just the pinball is broken on latest main. Looking into it.

**Comment by AlpyneDreams** [comment]
Looks like it might just be an issue with the apitrace. It looks the same on 2c56a1af, something very wrong here.

<img src="https://user-images.githubusercontent.com/3376691/234160940-55e4eddd-be15-4eed-85e4-f3a5e56cf97d.png" width=400>

**Comment by AlpyneDreams** [comment]
Yeah, looks like that was just an apitrace issue. The real game runs okay except for missing texture on the titular "pin ball"

**Comment by AlpyneDreams** [comment]
lol they have a funny cubemap

**Comment by AlpyneDreams** [comment]
The VS has the following decls in d3d9-speak which seems to match what it's asking for...
```
dcl_position v0
dcl_normal v3
dcl_color v5
dcl_texcoord v7
dcl_texcoord1 v8
 ```

and yet the actual shader code uses `v4` (POINTSIZE) where I think it's supposed to use `v3` (NORMAL) and it uses `v7` (TEXCOORD0) which, while technically valid, it probably should be using `v5` (COLOR) instead there. 

So it doesn't actually use `v3` or `v5` despite declaring them. Will compare with native.

**Comment by AlpyneDreams** [comment]
For some reason the game was also broken by [this change](https://github.com/AlpyneDreams/d8vk/commit/8db47e7da7b232c6085816ef774698df332aebdc#diff-0c2acce8799dde56ec15c461c0297b5c766d2c6dfabc970f36e7f08e8114e003) which is pretty weird since that should be correct.

**Comment by AlpyneDreams** [comment]
Seems like we need to add a private ref to textures somewhere so they don't get destroyed. However, I have no idea where that would be.

I've tried state blocks but that doesn't seem to fix it, as far as I can tell the game doesn't capture a non-null texture in its state blocks.

**Comment by AlpyneDreams** [comment]
Okay, seems like the refcount thing was only an issue on debug builds. Maybe something is not being initialized right.

As for the pinball, it works now :)
I added a config option to force override the VS decl, which is a total hack, but it works. I still don't know why the way this game was using vertex inputs worked on native but not here, and I'm not eager to find out.

![image](https://user-images.githubusercontent.com/3376691/234512077-b5ba7493-ceb9-4a33-89be-01aadbade0f0.png)
