### ISSUE TITLE
Storing DEFAULT buffers in MANAGED pool

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#135]
Previous title: [Upstream?] Buffer performance panic in water sample and Motor City Online
![image](https://user-images.githubusercontent.com/3376691/232229999-647ac5e8-f5ca-40f9-a92b-b0e00c6f3a0b.png)

Edit: See below.
~~Supposedly the issue is many writes to a non-writeonly buffer.~~

~~Is instantly fixed by `apiTraceMode`. As we did for Motor City Online (which treats d3d8 like it's GL) #125. So We have to just determine if this is an upstream issue or just an inherent setting we're going to have to set per-game if they try to do a lot of buffer writes.~~

**Comment by AlpyneDreams** [comment]
Okay so we have learned that the real fix is disabling direct buffer mapping. We might want to make that the default behavior.

**Comment by AlpyneDreams** [comment]
This will also fix new chugging introduced by Commands 3 (+ probably others) that have their perf borked by NOOVERWRITE being disabled.

**Comment by AlpyneDreams** [comment]
Josh suggets maybe make vertex and index buffers always be MANAGED if games are gonna do stuff with them like this. Instead of disabling direct buffer mapping. At least maybe only for DYNAMIC buffers...? idk. But we gotta pick something.

**Comment by AlpyneDreams** [comment]
Winter: Perf is better in MCO with DBM disabled compared to apitracemode, but the quads look like tris again... The NOOVERWRITE bit apparently cancelled out the perf from apitrace mode. There are so many variables here.

**Comment by WinterSnowfall** [comment]
> The NOOVERWRITE bit apparently cancelled out the perf from apitrace mode.

Yes, we should probably remember to enable direct buffer mapping for this game if disabling it becomes the new default. The NOOVERWRITE bit will have to be reverted for this game to be anything other than a slideshow.

P.S.: Turns out a lot of games are now slideshows due to the NOOVERWRITE bit, so it's not really a good option to enable it globally at least.

**Comment by AlpyneDreams** [comment]
> P.S.: Turns out a lot of games are now slideshows due to the NOOVERWRITE bit, so it's not really a good option to enable it globally at least.

Yep, reverted.

Now the question of whether to do the DEFAULT -> MANAGED thing or just disable DBM. They will have the same effect in preventing DBM but the former might gain some perf? Not clear.

**Comment by AlpyneDreams** [comment]
Disabling DBM programmatically would be annoying so I am opting to instead remap DEFAULT to MANAGED in  3b029ec0a28d5bc43c007166905c374caf88d892. Hopefully this does not break any games.

**Comment by AlpyneDreams** [comment]
The flickering in #130 and the performance of the water sample are seemingly fixed now.

**Comment by WinterSnowfall** [comment]
This breaks Motor City Online, which shows half quads again. The game seems to be very picky when it comes to VB/IB use.

**Comment by AlpyneDreams** [comment]
> This breaks Motor City Online, which shows half quads again. The game seems to be very picky when it comes to VB/IB use.

Of course it does

**Comment by WinterSnowfall** [comment]
If we ultimately decide to go down this road, the disable direct buffer mapping workarounds for Commandos 3 and Red Faction are superfluous and can be removed from config.cpp. I've tested both games and they works just fine without the workaround.

I've also done some general regression testing and haven't yet come across any noticeable performance degradation due to remapping DEFAULT to MANAGED.

**Comment by WinterSnowfall** [comment]
The performance problems we've had in 3DMark2001 SE with the High Detail Car Chase benchmark are now sorted. I think we're definitely doing something right.

**Comment by AlpyneDreams** [comment]
Games currently broken by this change:
- [x] Motor City Online - fixed in c815aa8fcb0a1d81e784b44603825c66a461b7ba
- [x] Brigade E5: New Jagged Union - fixed in 0387038670103d578348e907ee142abd1348e25d
- [x] Supreme Ruler 2020 - fixed in cd5b89b8b4696a29b23b2a954cb00a6c9c26cff0
- [x] Railroad Tycoon 3 - fixed in f6316a77cb15168834a9e4d0df8bc66b0e20ef07

**Comment by WinterSnowfall** [comment]
+ Railroad Tycoon 3
+ Incoming Forces (arguably the game is broken in many other ways and will need further looking into anyway)

I'll append here if I notice anything else.

**Comment by AlpyneDreams** [comment]
I'll close this issue for now since all games except Incoming Forces (#100) are fixed, and that one needs its own issue. If any other games are broken by this, open a new issue!
