### ISSUE TITLE
Games known to be broken mega-issue

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#147]
## If you have any details beyond the name of the game, please [create an issue](https://github.com/AlpyneDreams/d8vk/issues/new/choose).
Do not post the names of any games that work already. Only **broken** games in this thread.

**Comment by AlpyneDreams** [comment]
- [ ] Chaos Legion - black screen
- [ ] See [here](https://github.com/AlpyneDreams/d8vk/issues/75#issuecomment-1482666350) for more

**Comment by illusioon** [comment]
Obscure (254460) still doesn't work.

**Comment by WinterSnowfall** [comment]
> Obscure (254460) still doesn't work.

I got a hold of the demo, but it crashes both with d8vk and WineD3D for me :man_shrugging:.

**Comment by WinterSnowfall** [comment]
@AlpyneDreams I feel like we should probably close this, now that upstreaming is on the horizon? Each problematic game should have a proper issue of its own. 

Also, it feels like we've already exhaustively tested a large population of d3d8 games (clearly all the more prolific ones), so there shouldn't be any major surprises anyway.

**Comment by sparty411** [comment]
Both Call of Duty, and Call of Duty United offensive crash to desktop when launched.

**Comment by WinterSnowfall** [comment]
> Both Call of Duty, and Call of Duty United offensive crash to desktop when launched.

Call of Duty uses the id Tech 3 engine, therefore OpenGL. I'm not aware of any d3d8 support present here.

**Comment by sparty411** [comment]
I apologize, you're right. Not sure why I had this impression. Disregard :p

**Comment by sparty411** [comment]
> > Both Call of Duty, and Call of Duty United offensive crash to desktop when launched.
> 
> Call of Duty uses the id Tech 3 engine, therefore OpenGL. I'm not aware of any d3d8 support present here.

I apologize, you're right. Not sure why I had this impression. Disregard :p

**Comment by triatomic** [comment]
Star Trek - Armada II black screens after intro is played

**Comment by WinterSnowfall** [comment]
> Star Trek - Armada II black screens after intro is played

That's a ddraw problem, not something we can fix. This particular game has a very "wonderful" dual rendering system, where the menus are rendered using ddraw and only the in-game engine relies on d3d8. You'll need something like [cnc-ddraw](https://github.com/FunkyFr3sh/cnc-ddraw) together with d8vk to get the game to behave properly.

**Comment by triatomic** [comment]
> > Star Trek - Armada II black screens after intro is played
> 
> That's a ddraw problem, not something we can fix. This particular game has a very "wonderful" dual rendering system, where the menus are rendered using ddraw and only the in-game engine relies on d3d8. You'll need something like [cnc-ddraw](https://github.com/FunkyFr3sh/cnc-ddraw) together with d8vk to get the game to behave properly.

oh wow that's bad thanks for the heads up

**Comment by triatomic** [comment]
> > Star Trek - Armada II black screens after intro is played
> 
> That's a ddraw problem, not something we can fix. This particular game has a very "wonderful" dual rendering system, where the menus are rendered using ddraw and only the in-game engine relies on d3d8. You'll need something like [cnc-ddraw](https://github.com/FunkyFr3sh/cnc-ddraw) together with d8vk to get the game to behave properly.

can you tell me how to get cnc-ddraw and d8vk to work together in this game ?
cnc-ddraw is a ddraw to d3d9 wrapper fyi

**Comment by HonScottoSolo** [comment]
> > > Star Trek - Armada II black screens after intro is played
> > 
> > 
> > That's a ddraw problem, not something we can fix. This particular game has a very "wonderful" dual rendering system, where the menus are rendered using ddraw and only the in-game engine relies on d3d8. You'll need something like [cnc-ddraw](https://github.com/FunkyFr3sh/cnc-ddraw) together with d8vk to get the game to behave properly.
> 
> can you tell me how to get cnc-ddraw and d8vk to work together in this game ? cnc-ddraw is a ddraw to d3d9 wrapper fyi

This may require DXVK's dx9 too.

**Comment by WinterSnowfall** [comment]
> can you tell me how to get cnc-ddraw and d8vk to work together in this game ? 

By "together" I didn't mean at the same time. You'll need to use *something* that fixes the ddraw black screen problem in the menu. Once you get past the menu everything will work as expected and d8vk willl be loaded, since the game switches to d3d8.

> cnc-ddraw is a ddraw to d3d9 wrapper fyi

... or to OpenGL, fyi.

> This may require DXVK's dx9 too

Not really. The goal here is not to get both ddraw and d3d8 onto dxvk/d8vk, but rather fix the games's black screen menu problem.

**Comment by ElTioRata** [comment]
Spider-Man (2002) - Black screen and CTD.
Last .log line: "D3D9SwapChainEx: Failed to recreate swap chain: VK_ERROR_NATIVE_WINDOW_IN_USE_KHR"

**Comment by WinterSnowfall** [comment]
> Spider-Man (2002) - Black screen and CTD

The game is known to work fine minus some corruption during cinematics. See https://github.com/AlpyneDreams/d8vk/issues/109.

> "D3D9SwapChainEx: Failed to recreate swap chain: VK_ERROR_NATIVE_WINDOW_IN_USE_KHR"

Might want to keep an eye on https://github.com/doitsujin/dxvk/issues/3865 for that bit.
