### ISSUE TITLE
CI builds show the wrong version number

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#150]
Title.

**Comment by WinterSnowfall** [comment]
I've had a (belated) look over this and GitHub tags don't seem to propagate correctly onto the repo's git metadata (namely their timestamps are all over the place). 

What we can try is to have the next tag created locally and then pushed to GitHub - hopefully that will push the right timestamp metadata along with it, at least for the tag in question, and should fix versioning on future dev builds, regardless of them being offline or CI.
