### ISSUE TITLE
Question Request for the FAQs from the Wiki

### ISSUE THREAD

**Issue by John-Enigma** [AlpyneDreams/d8vk#153]
I wanna request a FAQ:

_Is d8vk better than dgVoodoo2 and nGlide?_

**Comment by WinterSnowfall** [comment]
It's never a good idea to compare apples to oranges.

**nGlide** translates Glide to d3d9 (or Vulkan in newer versions), and has nothing to do with d3d8.

**dgVoodoo2** is an marvelous and intricate piece of software that provides a lot of compatibility options for both Glide, ddraw and d3d1-d3d9 games. While you can use it with d3d8 games, it's not particularly targeted at being used with Wine or on Linux, nor does it translate anything to Vulkan or OpenGL (so you can't use it as a stand-alone solution on Linux).

**d8vk** provides an extension of dxvk's goals and strengths onto d3d8, in short.

If you're gaming on Linux it should ideally be the best alternative for any d3d8 game, that is its ultimate goal. Arguably that's already the case for a lot of games, but the project is still under active development and there is some room for improvement. The issue tracker is a good place to check for any pending issues or work yet to be done.

I hope it's more clear now why neither of these comparisons are on the Wiki page.

**Comment by John-Enigma** [comment]
I understand now. 

Thank you for the explanation!
