### ISSUE TITLE
The Da Vinci Code (2006) - Character polygons stretch and fall apart constantly

### ISSUE THREAD

**Issue by Mephistople** [AlpyneDreams/d8vk#154]
The Da Vinci Code (2006) - Character polygons stretch and fall apart constantly

So this is a issue that has long been present in regular wine and seems that D8VK for the moment can't render any better.
Basically your playable character polygons stretch and fall apart constantly.
The issue is present from the first level.

![The Da Vinci Code Issues 1](https://github.com/AlpyneDreams/d8vk/assets/53997310/8b5d1c42-1751-4a80-9919-a29b3a2ec9ab)
![The Da Vinci Code Issues 2](https://github.com/AlpyneDreams/d8vk/assets/53997310/4a20ed17-92b2-42b4-9405-c103fedc1986)

### Software information
The Da Vinci Code (2006)

### System information
- GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
- Driver: 530.41.03
- Wine version: 8.7 Staging
- D8VK version: [e1df54c](https://github.com/AlpyneDreams/d8vk/commit/e1df54ceaa4bdae12124ce4e638bccf641a34fa6)

### Apitrace file(s)
[Slayer.trace.tar.gz](https://mega.nz/file/2cd0mTxB#QVGUIgmo94xQ_yfq4UwCl_6B8bUjxWCoXHfEEEm8bL4)

### Log files
[Slayer_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11445227/Slayer_d3d8.log)

**Comment by WinterSnowfall** [comment]
As a note, #100 might be the same underlying issue, or something related. It's the only other instance of "vertex surrealism" I'm aware of (it also happens with WineD3D).

**Comment by dungeon007** [comment]
He, he, i would bet that The Da Vinci Code is one of these apps that suffers from WINE's msvcrt & friends sse2 issue.

**Comment by Mephistople** [comment]
Thanks dungeon007 that was really helpful.
Setting "msvcr71.dll" to native in winecfg and d3d8.managedBufferPlacement = False
made the game work :)

**Comment by dungeon007** [comment]
Tip to the moron and its ignorant supporter 🤣 at https://github.com/doitsujin/dxvk/issues/4382

Quickest fix - **override msvcr70 as native**.
Longest fix - https://bugs.winehq.org/show_bug.cgi?id=27594
