### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by slr** [AlpyneDreams/d8vk#159]
> commit cae0a1cef3f4917cf525c5546da302ff5f968e8e (HEAD -> master, tag: v2.2, origin/master, origin/HEAD)

fails to build with such errors:

> Found ninja-1.10.1 at /usr/bin/ninja
[15/289] Compiling C++ object src/wsi/libwsi.a.p/wsi_edid.cpp.obj
FAILED: src/wsi/libwsi.a.p/wsi_edid.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/wsi/libwsi.a.p -Isrc/wsi -I../../../src/wsi -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -I../../../subprojects/libdisplay-info/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/wsi/libwsi.a.p/wsi_edid.cpp.obj -MF src/wsi/libwsi.a.p/wsi_edid.cpp.obj.d -o src/wsi/libwsi.a.p/wsi_edid.cpp.obj -c ../../../src/wsi/wsi_edid.cpp
In file included from ../../../src/wsi/../util/log/log.h:8,
                 from ../../../src/wsi/wsi_edid.cpp:10:
../../../src/wsi/../util/log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/wsi/../util/log/log.h:8,
                 from ../../../src/wsi/wsi_edid.cpp:10:
../../../src/wsi/../util/log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/wsi/../util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/wsi/../util/log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[17/289] Compiling C++ object src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj
FAILED: src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/wsi/libwsi.a.p -Isrc/wsi -I../../../src/wsi -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -I../../../subprojects/libdisplay-info/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj -MF src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj.d -o src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj -c ../../../src/wsi/win32/wsi_window_win32.cpp
In file included from ../../../src/wsi/win32/../../util/log/log.h:8,
                 from ../../../src/wsi/win32/wsi_window_win32.cpp:5:
../../../src/wsi/win32/../../util/log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/wsi/win32/../../util/log/log.h:8,
                 from ../../../src/wsi/win32/wsi_window_win32.cpp:5:
../../../src/wsi/win32/../../util/log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/wsi/win32/../../util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/wsi/win32/../../util/log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[19/289] Compiling C++ object src/util/libutil.a.p/util_fps_limiter.cpp.obj
FAILED: src/util/libutil.a.p/util_fps_limiter.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../src/util -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/util/libutil.a.p/util_fps_limiter.cpp.obj -MF src/util/libutil.a.p/util_fps_limiter.cpp.obj.d -o src/util/libutil.a.p/util_fps_limiter.cpp.obj -c ../../../src/util/util_fps_limiter.cpp
In file included from ../../../src/util/util_fps_limiter.cpp:3:
../../../src/util/thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/util/util_fps_limiter.cpp:3:
../../../src/util/thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/util/thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/util/thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[20/289] Compiling C++ object src/util/libutil.a.p/util_gdi.cpp.obj
FAILED: src/util/libutil.a.p/util_gdi.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../src/util -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/util/libutil.a.p/util_gdi.cpp.obj -MF src/util/libutil.a.p/util_gdi.cpp.obj.d -o src/util/libutil.a.p/util_gdi.cpp.obj -c ../../../src/util/util_gdi.cpp
In file included from ../../../src/util/log/log.h:8,
                 from ../../../src/util/util_gdi.cpp:2:
../../../src/util/log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/util/log/log.h:8,
                 from ../../../src/util/util_gdi.cpp:2:
../../../src/util/log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/util/log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[21/289] Compiling C++ object src/wsi/libwsi.a.p/win32_wsi_monitor_win32.cpp.obj
FAILED: src/wsi/libwsi.a.p/win32_wsi_monitor_win32.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/wsi/libwsi.a.p -Isrc/wsi -I../../../src/wsi -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -I../../../subprojects/libdisplay-info/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/wsi/libwsi.a.p/win32_wsi_monitor_win32.cpp.obj -MF src/wsi/libwsi.a.p/win32_wsi_monitor_win32.cpp.obj.d -o src/wsi/libwsi.a.p/win32_wsi_monitor_win32.cpp.obj -c ../../../src/wsi/win32/wsi_monitor_win32.cpp
In file included from ../../../src/wsi/win32/../../util/log/log.h:8,
                 from ../../../src/wsi/win32/wsi_monitor_win32.cpp:4:
../../../src/wsi/win32/../../util/log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/wsi/win32/../../util/log/log.h:8,
                 from ../../../src/wsi/win32/wsi_monitor_win32.cpp:4:
../../../src/wsi/win32/../../util/log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/wsi/win32/../../util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/wsi/win32/../../util/log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[22/289] Compiling C++ object src/util/libutil.a.p/util_luid.cpp.obj
FAILED: src/util/libutil.a.p/util_luid.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../src/util -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/util/libutil.a.p/util_luid.cpp.obj -MF src/util/libutil.a.p/util_luid.cpp.obj.d -o src/util/libutil.a.p/util_luid.cpp.obj -c ../../../src/util/util_luid.cpp
In file included from ../../../src/util/./log/log.h:8,
                 from ../../../src/util/util_luid.cpp:4:
../../../src/util/./log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/util/./log/log.h:8,
                 from ../../../src/util/util_luid.cpp:4:
../../../src/util/./log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/util/./log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/util/./log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
[23/289] Compiling C++ object src/util/libutil.a.p/util_sleep.cpp.obj
FAILED: src/util/libutil.a.p/util_sleep.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../src/util -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/util/libutil.a.p/util_sleep.cpp.obj -MF src/util/libutil.a.p/util_sleep.cpp.obj.d -o src/util/libutil.a.p/util_sleep.cpp.obj -c ../../../src/util/util_sleep.cpp
In file included from ../../../src/util/util_sleep.h:3,
                 from ../../../src/util/util_sleep.cpp:1:
../../../src/util/thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/util/util_sleep.h:3,
                 from ../../../src/util/util_sleep.cpp:1:
../../../src/util/thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/util/thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/util/thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
../../../src/util/util_sleep.cpp: In member function ‘void dxvk::Sleep::systemSleep(dxvk::Sleep::TimerDuration)’:
../../../src/util/util_sleep.cpp:118:12: error: ‘std::this_thread’ has not been declared
  118 |       std::this_thread::sleep_for(duration);
      |            ^~~~~~~~~~~
[24/289] Compiling C++ object src/util/libutil.a.p/util_shared_res.cpp.obj
FAILED: src/util/libutil.a.p/util_shared_res.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../src/util -I../../../include -I../../../include/vulkan/include -I../../../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/util/libutil.a.p/util_shared_res.cpp.obj -MF src/util/libutil.a.p/util_shared_res.cpp.obj.d -o src/util/libutil.a.p/util_shared_res.cpp.obj -c ../../../src/util/util_shared_res.cpp
In file included from ../../../src/util/log/log.h:8,
                 from ../../../src/util/util_shared_res.cpp:2:
../../../src/util/log/../thread.h:261:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  261 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
In file included from ../../../src/util/log/log.h:8,
                 from ../../../src/util/util_shared_res.cpp:2:
../../../src/util/log/../thread.h:279:10: error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_for(std::unique_lock<dxvk::mutex>& lock, const std::chrono::duration<Rep, Period>& timeout) {
      |          ^~~~~~~~~
../../../src/util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../../../src/util/log/../thread.h:292:54: error: ‘std::cv_status’ has not been declared
  292 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by WinterSnowfall** [comment]
The commit you are referring to is part of dxvk, not d8vk. d8vk has not yet been rebased on top of dxvk 2.2, but will most likely be at some point in the future.

**Comment by slr** [comment]
oops, my fault.

have used

`git clone --recursive https://github.com/doitsujin/dxvk.git`
