### ISSUE TITLE
d8vk upstream?

### ISSUE THREAD

**Issue by begin-theadventure** [AlpyneDreams/d8vk#16]
Will d8vk ever be merged with DXVK?

**Comment by Blisto91** [comment]
It's being made in a way so it's mergable with dxvk.
But nothing has definitely been decided yet afaik and it's up to the dxvk devs of they want to include it at some point.
But the idea haven't been rejected yet at least

**Comment by eszlari** [comment]
A TODO list would be interesting for following the progress.

**Comment by orowith2os** [comment]
Indeed. @AlpyneDreams do you have any comments on the bugs that should be resolved before attempting to upstream?

**Comment by AlpyneDreams** [comment]
> Indeed. @AlpyneDreams do you have any comments on the bugs that should be resolved before attempting to upstream?

See doitsujin/dxvk#3411

**Comment by AlpyneDreams** [comment]
Merging soon...
