### ISSUE TITLE
How to install for Proton Flatpak?

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [AlpyneDreams/d8vk#162]
I'm using Steam and Proton in the Flatpak version. How should I install d8vk for them?

**Comment by AlpyneDreams** [comment]
In that case I would recommend setting your Steam launch parameters to `WINEDLLOVERRIDES=d3d8=n,b %command%` and then place `d3d8.dll` in the same folder as the exe file of the game you want to run in your steamapps.
