### ISSUE TITLE
d3d9 dll?

### ISSUE THREAD

**Issue by shmerl** [AlpyneDreams/d8vk#170]
Recent updates started building d3d9.dll again instead of static build. Is it needed vs upstream dxvk dll or it's just a build artifact that's not needed to be used?

**Comment by WinterSnowfall** [comment]
The former, as in it is a prerequisite for upstreaming. If you want to go back to a statically linked single dll, you can revert this revert: c6ba9e1. Haven't tested it myself but it shouldn't cause any issues with future updates.

Edit: Actually you'll need to revert all these 3: c6ba9e1, 50d232d and 0a46abf.

**Comment by AlpyneDreams** [comment]
Yeah, from now on you're gonna need to copy d3d9.dll again.

We'll need to update the documentation I suppose.

**Comment by shmerl** [comment]
I see, thanks. Are you preparing to upstream it soon?

**Comment by Blisto91** [comment]
It is a work in progress. Dunno if the merge will happen soon

**Comment by shmerl** [comment]
Any news on merging or what is blocking it? It's been a while.

**Comment by Blisto91** [comment]
There is a goal of having it merged for dxvk 2.4

**Comment by AlpyneDreams** [comment]
Merge is done!
