### ISSUE TITLE
Trainz v1.1.1/UTC crashes

### ISSUE THREAD

**Issue by HunterCZ122** [AlpyneDreams/d8vk#173]
### Software information
Trainz v1.1.1/UTC
Demo is obtainable [here](https://www.gamepressure.com/download.asp?ID=1112), but keep in mind that I use Czech retail Level 115 CD-ROM version, which hopefully shouldn't be that different (it has same engine version).

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver: 525.47.27
- Wine version: Wine-GE-Proton8-8
- DXVK version: d8vk-v1.0 (also tried latest builds from actions, no luck)

### Apitrace file(s)
That game hates apitrace for some reason, and gives me just blank 7.6KiB apitrace.

### Log files
[trainz_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11952182/trainz_d3d8.log)

All I get is unfortunately this:
![Screenshot_20230704_225216](https://github.com/AlpyneDreams/d8vk/assets/23011428/1c430682-7b7d-42ba-8d79-442cd7581b54)
It works fine with WineD3D.
Both adding d3d8.dll next to game's executable or SysWOW64 directory in Wine prefix doesn't work.
Game is launched with `WINEDLLOVERRIDES=d3d8=n,b` env var.

EDIT: You also need to run `winetricks mfc42` otherwise the game and launcher will not work.

**Comment by WinterSnowfall** [comment]
Edit: Nevermind, the game itself doesn't appear to rely on MFC (I had assumed it did based on some screenshots).

In case it somehow does, then crashes are no surprise: #8

**Comment by HunterCZ122** [comment]
Moved to DXVK repo: https://github.com/doitsujin/dxvk/issues/4116
