### ISSUE TITLE
Castle Strike break when alt tabbing

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#175]
Alt tabbing in Castle Strike will make you not able to go ingame again. This is likely due to some upstream work from a rebase.

### Software information
Castle Strike

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: 8.12
- DXVK version: Master and https://github.com/AlpyneDreams/d8vk/pull/172 
Remaining resources is lower with the latter 
### Apitrace file(s)
[Castlestrike.tar.gz](https://github.com/AlpyneDreams/d8vk/files/12008913/Castlestrike.tar.gz)
One with d8vk and one with wined3d

### Log files
[Castlestrike_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/12008849/Castlestrike_d3d8.log)
[Castlestrike_d3d9.tar.gz](https://github.com/AlpyneDreams/d8vk/files/12008850/Castlestrike_d3d9.tar.gz)

**Comment by WinterSnowfall** [comment]
The game apparently expects device lost signaling on alt+tab (as can be seen in the WineD3D trace):

![DeviceLost](https://github.com/AlpyneDreams/d8vk/assets/6306593/45dbab3a-abaa-4f98-9958-e2b4032aed7b)

It's worth checking out if @K0bin's d3d9 config option does anything in this case.

**Comment by Blisto91** [comment]
Forgot to note i already tried with `d3d9.deviceLossOnFocusLoss` and it has the same issue.
Here is trace with it enabled [Castlestrike-DeviceLost.trace.tar.gz](https://github.com/AlpyneDreams/d8vk/files/12017036/Castlestrike-DeviceLost.trace.tar.gz)

**Comment by WinterSnowfall** [comment]
Turns out we were not releasing state blocks on calls to D3D8Device::DeleteStateBlock(), rather only removing their references from ye' olde state block set. That kept the D3D9 resources around as well, which caused the issues on device Reset. Should be fixed now in #172.

**Comment by Blisto91** [comment]
Confirmed fixed
