### ISSUE TITLE
Harry potter goblet of fire PC - issues 

### ISSUE THREAD

**Issue by Chip-Biscuit** [AlpyneDreams/d8vk#183]
We have unlocked the frame rate in this game but there are some issues that need to be fixed if you could watch these videos and see if this would be something you would be interested in fixing let me know either way :)

this is using d8vk on windows 10 (d3d8.dll) and (dxvk.conf) 
 
there is also no audio to these videos intentionally 

these videos where using d8vk which changed the renderer from dx8 to dx9 as we thought it may fix the issues but unfortunately not

in the first video you should be able to use the spell to retract the big Bubotuber and fling it onto the walkway so it clears the path but at the moment it just blows up and then you cannot progress the game any further on herbology level . While this doesn't break progression on the forbidden forest level story wise it does break the collectables aspect of the level.

the second video the maze task once you get past the maze section and go to the chase sequence after the cutscene Harry's model disappears and makes it impossible to complete the rest of the level as the whole game then freezes at this point with the player invisible.

https://github.com/AlpyneDreams/d8vk/assets/79383464/b9f77e84-8180-4002-ac5d-ff76e366ab70

https://github.com/AlpyneDreams/d8vk/assets/79383464/bde78cde-4711-4631-aa68-69ffc7378958

**Comment by WinterSnowfall** [comment]
Same as on the other issue you've raised, please fill out the issue template. What is rather essential for us to be able to look further into this is an apitrace capturing the issue. Information about your d8vk version, card, OS and driver are also important.

While videos offer a visual representation of what is wrong, apitraces capture the d3d calls made by the game (and you can also play them back to see what is happening, much like videos).

> these videos where using d8vk which changed the renderer from dx8 to dx9 as we thought it may fix the issues but unfortunately not

Not sure what you mean here. D8VK will not magically change the API level. If you are not seeing D3D8 as the listed API then the game is actually using D3D9 and you should report this upstream, on the [dxvk issue tracker.](https://github.com/doitsujin/dxvk/issues)

PCGW seems to indicate this is indeed a D3D9 game: https://www.pcgamingwiki.com/wiki/Harry_Potter_and_the_Goblet_of_Fire

Also note that if these are game bugs that are also present on Windows, there's most likely nothing that can be done to address them from a d3d perspective.
