### ISSUE TITLE
House of the Dead III - Lisa's hair detaches from her head

### ISSUE THREAD

**Issue by SeongGino** [AlpyneDreams/d8vk#193]
### Software information
The House of the Dead III (PC)

### System information
- GPU: NVIDIA Geforce RTX 3060 Ti
- Driver: NVIDIA 545.29.02
- Wine version: Wine-GE-Proton8-23
- DXVK version: 1.0

### Apitrace file(s)
[hod3pc.5.trace.tar.xz](https://drive.google.com/file/d/1gFtPT4Ekd98H-oc_Mr6VgWi9T0LFYLNh/view?usp=sharing)

### Log files
n/a

The first stage that the character appears (which is stage 2... which is the first real stage, but semantics aside), her hair detaches from her head - almost like it's frozen where it first appears in the shot.
Examples for visual aid, both from Stage 2:
![2023_11-22 195839](https://github.com/AlpyneDreams/d8vk/assets/7321839/c59b985d-d416-4fdf-a9f9-693142e3efe6)
![2023_11-22 195852](https://github.com/AlpyneDreams/d8vk/assets/7321839/a2d20a27-4ad3-495f-a6a9-3d56f4044a3f)

NOTE: Though the apitrace is attached with WineD3D as instructed, some facial models are broken under it and I'm not sure if the resulting trace is reproduced perfectly:
(subtitles glitch here happens on D8VK too)
![2023_11-22 202805-THE HOUSE OF THE DEAD 3](https://github.com/AlpyneDreams/d8vk/assets/7321839/ef21c3f8-5abe-4928-9a73-ae6fa03b2b65)
![2023_11-22 202841-THE HOUSE OF THE DEAD 3](https://github.com/AlpyneDreams/d8vk/assets/7321839/b3436ab2-d79e-496e-8936-c827c371f2c3)
These issues aren't reproduced in dgvoodoo2-through-DXVK.

**Comment by WinterSnowfall** [comment]
@SeongGino Thank you for the very detailed report and the trace. Can confirm I'm seeing the same problem with missing/detached hair.

> NOTE: Though the apitrace is attached with WineD3D as instructed, some facial models are broken under it and I'm not sure if the resulting trace is reproduced perfectly

The trace is good as far as I can tell, it's WineD3D that is even more broken than d8vk in this case:

![WineD3D](https://github.com/AlpyneDreams/d8vk/assets/6306593/6d3bb783-8aa1-4615-973f-93740ac52b14)

I've looked at the scene and haven't noticed anything off in terms of calls. At least not too odd... the game queries device capabilities and supported texture formats multiple times **on each frame**, which is certainly... an interesting design. 

There's no ProcessVertices involved at least, which would have been my first guess. I guess this needs the RenderDoc treatment. The game seems to be entirely reliant on fixed function, so perhaps there are some inaccuracies in dxvk's shaders.

**Comment by mrdeathjr28** [comment]
In my case resolve heavy stutter and now is more playable

**Comment by SeongGino** [comment]
Has this problem been addressed? I haven't seen any notification on about a commit directly addressing this particular issue.

**Comment by mrdeathjr28** [comment]
In my case appear this:

![thod3a](https://github.com/AlpyneDreams/d8vk/assets/6601480/7653e0e3-59ad-4aa4-9eca-db035c02b636)

**Comment by WinterSnowfall** [comment]
> Has this problem been addressed? I haven't seen any notification on about a commit directly addressing this particular issue.

Lisa's hair is still broken, so no, the rebase and merge with dxvk didn't improve the situation here. But no worries, we'll get to it eventually.

**Comment by SeongGino** [comment]
> > Has this problem been addressed? I haven't seen any notification on about a commit directly addressing this particular issue.
> 
> Lisa's hair is still broken, so no, the rebase and merge with dxvk didn't improve the situation here. But no worries, we'll get to it eventually.

Which is exactly what I was referring to, thank you. I will continue to pray for the recovery of Lisa's hair in silence in the meantime. :)

**Comment by mrdeathjr28** [comment]
> > Has this problem been addressed? I haven't seen any notification on about a commit directly addressing this particular issue.
> 
> Lisa's hair is still broken, so no, the rebase and merge with dxvk didn't improve the situation here. But no worries, we'll get to it eventually.

well in my case appear this:

![thod3oha](https://github.com/AlpyneDreams/d8vk/assets/6601480/d570eb85-8ded-4223-a365-48153a3c9a23)

![thod3ohb](https://github.com/AlpyneDreams/d8vk/assets/6601480/e357d67c-ddf4-493d-9cce-f5ca8b29713c)

![thod3ohc](https://github.com/AlpyneDreams/d8vk/assets/6601480/d7f5c61a-76ab-4cb2-8711-586099ab56b4)

**Comment by WinterSnowfall** [comment]
We don't have the game, so only checked the trace. Probably worth rechecking in-game also at this point with latest dxvk master to see if it's fixed, as it appears to be based on @mrdeathjr28's screenshots.

**Comment by Blisto91** [comment]
Yea apparently the missing hair is baked in to the trace and shows also on native Windows. Wasn't checked before now

**Comment by SeongGino** [comment]
Checked with the artifact from doitsujin/dxvk `4b0c9c6`: no change, still yikes material.
![2024_07-09 014406](https://github.com/AlpyneDreams/d8vk/assets/7321839/975fdbca-06ac-4d63-af7f-af04f256f114)

That said, if it's merged, should we transfer this issue there or keep it to this repo? And not sure if that would necessitate another trace capture or not.

**Comment by WinterSnowfall** [comment]
> That said, if it's merged, should we transfer this issue there or keep it to this repo? And not sure if that would necessitate another trace capture or not.

If you have time, please move it over and close this one, yes. You don't need a new trace, attaching the existing one is fine.

**Comment by SeongGino** [comment]
Fair enough. Self-closing in favor of doitsujin/dxvk#4130
