### ISSUE TITLE
Enhancement: option for xBRZ texture filtering

### ISSUE THREAD

**Issue by telychko** [AlpyneDreams/d8vk#196]
Old games that running on DirectX8 often has low texture resolution. [Many of emulators](https://emulation.gametechwiki.com/index.php/Texture_filtering) solve the problem via HQ texture filtering. Here is [an example](https://www.youtube.com/watch?v=qaDZs7tJ9ow) of how it is implemented in DuckStation.

Would be great if such option could be implemented in D8VK.

**Comment by WinterSnowfall** [comment]
You very much already can force a desired anisotropy level via `d3d9.samplerAnisotropy = 16`, as you would in dxvk for d3d9 games. Games like (the original) Mafia which are stuck with bi/trilinear filtering by default benefit from it greatly. In fact, all of dxvk's d3d9 conf options are usable with d8vk as well.

The main goal of the project however is to ensure older games render accurately, not to enhance their visuals, so this won't ever be a builtin default. It is however something one can apply when needed, based on individual preferences.

**Comment by telychko** [comment]
I got your point. OK. Thank you for great work!
