### ISSUE TITLE
Mafia (2002)

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#20]
Reported by `@Xaero#6686` in LGD.
[Game_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9798281/Game_d3d9.log)

d3d8.log empty. Gonna need to get an apitrace or something.

**Comment by AlpyneDreams** [comment]
[steam-40990.log](https://github.com/AlpyneDreams/d8vk/files/9818837/steam-40990.log)

**Comment by Blisto91** [comment]
Game doesn't want to launch with apitrace 😢 
Also not on windows

**Comment by AlpyneDreams** [comment]
Reported working by esdras.

**Comment by Blisto91** [comment]
Can confirm that the game launches now
