### ISSUE TITLE
[Question] D3D9SwapChainEx: Failed to recreate swap chain: -13 on 6700 XT

### ISSUE THREAD

**Issue by grandshot** [AlpyneDreams/d8vk#201]
About a half year ago all works fine, but now it's just show white or black screen in all games. What could happen? Original DXVK still works with Dx9 games without issues mostly.

Tried to test with integrated intel, but result is same. By identical log can presume what Windows Graphic Settings just ignoring, and discrete card is used anyway.

### System information
- OS: WIndows 10
- GPU: AMD Radeon RX 6700 XT
- Driver: 2.0.294
- Vulkan: 1.3.270 

[Morrowind_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/14152821/Morrowind_d3d8.log)
[Game_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/14152861/Game_d3d8.log)

**Comment by WinterSnowfall** [comment]
Hmmm... -13 is VK_ERROR_UNKNOWN, so that doesn't say much about what's going on. No idea why you're getting this, but in all fairness AMD drivers don't get a lot of testing (if any) on Windows with d8vk. Something may have broken on that end, though I'd expect d3d9 games run with dxvk to exhibit the same issues if that's the case.

**Comment by grandshot** [comment]
>  Something may have broken on that end, though I'd expect d3d9 games run with dxvk to exhibit the same issues if that's the case.

FarCry with dxvk runs perfectly, what i can prove by log.

[FarCry_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/14154222/FarCry_d3d9.log)

**Comment by grandshot** [comment]
For experiment I produced a clean install of Windows 11 to another physical drive. Nothing changed, so that's exactly the latest AMD drivers is guilty. Crosire's dx9 wrapper works fine, just in case.
[game_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/14171892/game_d3d8.log)

**Comment by Blisto91** [comment]
fwiw some other dxvk games have the same crash issue with Windows AMD drivers from 23.10.2 and above. See https://github.com/doitsujin/dxvk/issues/3723 as an example.
23.8.2 should work
