### ISSUE TITLE
Indiana Jones and the Emperors Tomb crash before main menu

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#21]
Game crashes before it reaches the main menu. Doesn't happen with WINED3D

### Software information
Indiana Jones and the Emperors Tomb

### System information
- GPU: R9 380
- Driver: radv 22.2.1
- Wine version: Proton experimental
- DXVK version: https://github.com/AlpyneDreams/d8vk/commit/7050a4dd1f0f1091b917e4e9c80ba55a1a8dbcce (from CI artifacts)

### Apitrace file(s)
https://mega.nz/file/UwICCQDI#CMlqKg2MC-RKZlLs1Geubsab9fsDr17kLNoaSGnYJE0

### Log files
[indy_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9803917/indy_d3d9.log)

d3d8 log is empty

**Comment by AlpyneDreams** [comment]
Great issue! Will investigate soon.

**Comment by Blisto91** [comment]
With the latest version the game still crashes for me.
[indy_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/9841550/indy_d3d8.log)
[indy_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9841551/indy_d3d9.log)

Tho now the trace doesn't crash anymore. Just has some visual artifacts
<details>
  <summary>Click me</summary>
  
![Screenshot_20221021_203026](https://user-images.githubusercontent.com/47954800/197265376-65654215-a84a-41df-86c5-fdaa7b9ff328.png)
</details>

**Comment by Blisto91** [comment]
This works now! :tada:
