### ISSUE TITLE
Game A.I.M.2 Clan Wars

### ISSUE THREAD

**Issue by ghost** [AlpyneDreams/d8vk#210]
[AIMII_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/14774155/AIMII_d3d8.log)

The game crashed after the screensaver.

### System information
- GPU: GTX 1070
- Driver: 546.33
- Wine version: Windows 10
- DXVK version: Version 1.0 - Croaka-Cola Classic

### Log files
the log created by the game:
25- 3-2024 21:33:55:226 EXCEPTION:->CMMApp::InitGraphic->CMMApp::Init

**Comment by ghost** [comment]
The game broke down due to the fact that I set compatibility with win98, after I turned it off, the game works fine.

**Comment by WinterSnowfall** [comment]
I have the game and can say it works just fine with Wine, aside from some minor crashing which seems to be a game bug. There's no issues with rendering at least, so nothing we can do about it in d8vk.

I remember there being an unofficial patch to address the crashing on modern systems, but it was buried somewhere on a modding forum if I recall correctly. There were fixed versions of `db.bat`, `db.ind` and `db.tab` which you had to drop in the game's install directory.
