### ISSUE TITLE
Arma: Cold War Assault

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#22]
[steam-65790.log](https://github.com/AlpyneDreams/d8vk/files/9818786/steam-65790.log)

**Comment by AlpyneDreams** [comment]
UpdateTexture implemented. We'll see if the issue persists.

**Comment by WinterSnowfall** [comment]
@AlpyneDreams Play-tested the game with a couple of single missions and a quick campaign intro. Looks and plays just fine now. We can close this issue.

**Comment by AlpyneDreams** [comment]
Awesome
