### ISSUE TITLE
3DMark 2001

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#25]
~~Crashes after nature test according to CME~~

Everything works, except for compatibility issues with Wine and the installer.

Tips:
- Use Wine 8.0 instead of latest
- Set texture mode to "32-bit" as "Compressed" does not work on Wine

**Comment by AlpyneDreams** [comment]
car chase high detail performs much worse with d8vk

**Comment by AlpyneDreams** [comment]
60443 points with wined3d vs 82050 with d8vk 💪 :D

**Edit**: New results:
| Implementation             | WineD3D                | d3d8to9 + dxvk (2.1) | **d8vk**           |
|----------------------------|------------------------|----------------------|--------------------|
| Score                      | 97134                  | 118033               | **144660**         |
| Car Chase - Low            | 1409.1 fps             | **2075.5 fps**       | 2017.5 fps     |
| Car Chase - High           | 352.1 fps              | 148.9 fps            | **553.8 fps**      |
| Dragothic - Low            | 1510.4 fps             | 1853.3 fps           | **2016.9 fps**     |
| Dragothic - High           | 807.6 fps              | 792.3 fps            | **1167.4 fps**     |
| Lobby - Low                | 1278.5 fps             | 1528.5 fps           | **1545.7 fps**     |
| Lobby - High               | 585.6 fps              | 523.3 fps            | **778.4 fps**      |
| Nature                     | 1012.4 fps             | 1708.6 fps           | **1943.4 fps**     |
| Fill Rate - Single Texture | **80163.2 MTexels/s**  | 64208.1 MTexels/s    | 62904.5 MTexels/s  |
| Fill Rate - Multitexturing | **159903.7 MTexels/s** | 97900.4 MTexels/s    | 96772.7 MTexels/s  |
| High Poly Count (1 light)  | 1335.1 MTris/s         | 2217.0 MTris/s       | **2375.5 MTris/s** |
| High Poly Count (8 lights) | 1267.6 MTris/s         | **2092.4 MTris/s**   | 1853.5 MTris/s     |
| Environment Bump Mapping   | 526.9 fps              | 1430.8 fps           | **2333.4 fps**     |
| DOT3 (Normal) Mapping      | 2025.1 fps             | 1608.9 fps           | **2331.6 fps**     |
| Vertex Shader              | 727.2 fps              | 788.7 fps            | **846.9 fps**      |
| Pixel Shader               | 1220.9 fps             | 1059.8 fps           | **1337.1 fps**     |
| "Advanced" Pixel Shader    | **4066.1 fps**         | 2808.6 fps (broken)  | 2544.7 fps         |
| Point Sprites              | **1193.9 MSprites/s**  | 1071.4 MSprites/s    | 987.5 MSprites/s   |

Specs:
- d8vk version: latest (bd394b8d6fdf09269fe48c5f103abcdd4f197cd4)
- Default settings, except textures set to 32-bit due to a Wine bug
- GPU: RTX 3080 Ti Laptop
- Run in a Wine Desktop window on GNOME with background apps. Not the fairest environment.

**Comment by WinterSnowfall** [comment]
> Crashes after nature test according to CME

Retested with 0.10/latest master. On a full suite of tests it will consistently crash after the Fill Rate (Single-Texturing) test, with the following error:

![3DMarkError](https://user-images.githubusercontent.com/6306593/215067617-dc357f69-caa4-4888-a13e-8005c3700b3a.png)

It's not a problem with the test itself, because if you run it individually it works just fine, but rather with running multiple tests in sequence. After this error shows up no tests will run in 3DMark until you've restarted it, otherwise you'll see this error on each benchmark start attempt, regardless of chosen tests.

I've attached the error.log file for reference: [error.log](https://github.com/AlpyneDreams/d8vk/files/10518017/error.log)

**Comment by WinterSnowfall** [comment]
> car chase high detail performs much worse with d8vk

I've had a look at a trace, and I believe this is due to the atrociously high fixed function lights which are being set in particular frames (since we're not currently caching those).

**Comment by WinterSnowfall** [comment]
I have the distinct feeling whatever problem d8vk is hitting in the 3DMark High Detail Car Chase is the same as the one that can be observed in the "Water" D3D8 SDK sample app. Modes 1 to 4 of the sample (that appear to be using FF lights) perform abysmally, where as mode 5 (which appears to not use any lights) does not. My assumption may be wrong, but the sample app may still be useful in figuring out what is going on here.

**Comment by WinterSnowfall** [comment]
> > car chase high detail performs much worse with d8vk
> 
> I've had a look at a trace, and I believe this is due to the atrociously high fixed function lights which are being set in particular frames (since we're not currently caching those).

Whatever it was, looks like it's been fixed by storing DEFAULT buffers in MANAGED :tada: .

The crashing between tests is still a problem, and I can't run a full suite, as it usually crashes after the Lobby benchmark on a full run. With Wine 8.0+ it will crash with an assert, which leads me to believe this may be a winevulkan problem perhaps.

**Comment by AlpyneDreams** [comment]
> D8VK wrongly loads in memory each test (without clearing or reused memory from before, as that is what should normally happen here), assumes that every test is a new app, but it isnt... this goes like array in a single process, it is not a new app, it is the same app. Without handling that, this will grow and grow until It reaches 2GiB 32bit limit or about 3GB VM size and then normaly go out.,,, whenever that happens.

Hmm, yeah, it does appear to run out of memory, I don't remember it doing that originally, which is weird cause we shouldn't be leaking refs anymore.

**Comment by AlpyneDreams** [comment]
What's weird is that I don't see a lot of activity on the vidmem or sysmem heaps on the HUD. It's possible there's no leak and allocations are failing for some other reason. Apparently it fails on the 10th test no matter what you pick.

**Comment by AlpyneDreams** [comment]
> And D3D9 DXVK probably have to fix water to move in Advanced Pixel Shader test, that static water looks like some sort of shader issue. Happens with d3d8to9 too, so it is an d3d9 issue.

The water shader is now fixed as of 4a7c627e3dc7d706916b870cd1e15f510c3951fd.

No news on the memory leak but at least it's easy to work around for now.

**Comment by WinterSnowfall** [comment]
The memory leak/crash between tests appear to have been sorted by bd394b8, however there are still some issues to be fixed. I got this error right after the DOT3 bumpmap test now:

![image](https://user-images.githubusercontent.com/6306593/236741280-1a024f62-619a-4048-9a42-5eb7ccb5f68d.png)

Edit: It crashes consistently at this point with the above error. I did multiple runs.

**Comment by dungeon007** [comment]
Everything looks fine now for me on RADV.
So, i guess DOT3 crashing @WinterSnowfall must be something driver dependant. So maybe check it out if it just on nvidia or intel driver or so.

**Comment by dungeon007** [comment]
BTW, i run this inside Wine virtual window and default set, so was with something like:
 **WINE_D3D_CONFIG="renderer=gdi" wine explorer /desktop=3DMark2001,1024x768 3DMark2001SE.exe /nosplash**
 Maybe you are doing something different, with different res or so... then crash could happen, on changing res or something due to that...

**Comment by WinterSnowfall** [comment]
> **WINE_D3D_CONFIG="renderer=gdi" wine explorer /desktop=3DMark2001,1024x768 3DMark2001SE.exe /nosplash** 

Thank you for the suggestion, but that didn't help. What Wine version are you using?

**Comment by dungeon007** [comment]
WINE 8.0.1, mesa git, this artifact https://github.com/AlpyneDreams/d8vk/actions/runs/4911518631

Tried it again, but no i cant reproduce it on RADV.

**Comment by WinterSnowfall** [comment]
As I suspected, the latest versions of Wine apparently mucked something up. I tried it on Wine 8.1 and it works perfectly, so I guess we can close this now.

**Comment by mrdeathjr28** [comment]
In my case dont allow install, only show this message and console dont show anything rare

![3dmarkerr](https://user-images.githubusercontent.com/6601480/236842435-a948351c-30b2-42e3-acf7-4f0fdb86eeab.png)

**Comment by AlpyneDreams** [comment]
@mrdeathjr28 
Make sure d8vk is properly installed on your Wine prefix. You might have to set your Wine Windows version lower. Issues with the installer aren't really our department unfortunately.
