### ISSUE TITLE
Determine a good default value for MultiSampleQuality

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#31]
This value is D3D9-only and determines sample counts. Currently it is set to 0 but should probably be increased. Need to figure out what the possible options are and how they affect visuals.

See `DecodeMultiSampleType` in `d3d9_util.cpp`

**Comment by WinterSnowfall** [comment]
I believe 0 is fine and we shouldn't have to worry about it. In D3D9 the value appears to be used only in conjunction with [D3DMULTISAMPLE_NONMASKABLE](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dmultisample-type?redirectedfrom=MSDN), which is not present in D3D8.

> 
> Whether the display device supports maskable multisampling (more than one sample for a multiple-sample render-target format plus antialias support) or just non-maskable multisampling (only antialias support), the driver for the device provides the number of quality levels for the D3DMULTISAMPLE_NONMASKABLE multiple-sample type. Applications that just use multisampling for antialiasing purposes only need to query for the number of non-maskable multiple-sample quality levels that the driver supports.
> 
> The quality levels supported by the device can be obtained with the pQualityLevels parameter of [IDirect3D9::CheckDeviceMultiSampleType](https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3d9-checkdevicemultisampletype). Quality levels used by the application are set with the MultiSampleQuality parameter of [IDirect3DDevice9::CreateDepthStencilSurface](https://learn.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-createdepthstencilsurface) and [IDirect3DDevice9::CreateRenderTarget](https://learn.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-createrendertarget).

> pQualityLevels returns the number of device-specific sampling variations available with the given sample type. For example, if the returned value is 3, then quality levels 0, 1 and 2 can be used when creating resources with the given sample count. The meanings of these quality levels are defined by the device manufacturer and cannot be queried through D3D. For example, for a particular device different quality levels at a fixed sample count might refer to different spatial layouts of the sample locations or different methods of resolving. This can be NULL if it is not necessary to return the quality levels.
