### ISSUE TITLE
Indiana Jones and the Emperors Tomb

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#35]
Indy has gotten a new haircut i think and I'm not sure i like it.

<details>
  <summary>Screenshot</summary>
  
![Screenshot_20221022_145201](https://user-images.githubusercontent.com/47954800/197341209-3efbd2d4-d967-48c9-b52e-adbc5b223ed8.png)
</details>

### Software information
Indiana Jones and the Emperors Tomb

### System information
- GPU: R9 380
- Driver: radv 22.2.1
- Wine version: proton experimental
- D8VK version: https://github.com/AlpyneDreams/d8vk/commit/2f048dc41e867384fbe5a9a1d5d83bf64e0a86a4

### Apitrace file(s)
https://mega.nz/file/klRQWRiA#aWgsHgV6abUCXuQ2OBh9FSVbBFTAv_QZ3zK1hR-XbNw

### Log files
[indy_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9844442/indy_d3d9.log)

d3d8.log empty

**Comment by Blisto91** [comment]
Indy's bad hair day has been solved on latest master.
Some new issues have shown up tho. Alot of objects have black textures and Indy's body and animations are a bit malformed.
The trace in the original issue shows the issues.
<details>
  <summary>Screenshot of black textures:</summary>

![Screenshot_20221024_182553](https://user-images.githubusercontent.com/47954800/197604902-32f0fd09-3592-45be-a5ca-60e82a4e0fac.png)
</details>

Video of Indy:
https://youtu.be/ZQ4dejM59Dk

**Comment by AlpyneDreams** [comment]
My last two commits should have fixed this game. Let me know if everything works as expected so I can close the issue.

**Comment by Blisto91** [comment]
Game is looking good now. I have played a bit on my R9 380 without encountering a issue
