### ISSUE TITLE
GTA Vice City

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#37]
GTA Vice City crashes after new game loading screen. Doesn't happen with wined3d.

### Software information
GTA Vice City

### System information
- GPU: R9 380
- Driver: 22.2.1
- Wine version: WINE-GE 31
- D8VK version: https://github.com/AlpyneDreams/d8vk/commit/7cd4c8b37f563c37068be51e92b925730411b6c5

### Apitrace file(s)
https://mega.nz/file/50xxXA6T#dgJKdYr781jUSEFGKZEUaZ2F6rtnViZotvfvf2lzz-k
Reproduces in the trace

### Log files
[gta-vc_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9845313/gta-vc_d3d9.log)

d3d8 empty

**Comment by Blisto91** [comment]
Retested with latest master (https://github.com/AlpyneDreams/d8vk/commit/3c701a6b200675eaadab527a443b12ddec5a1a69) just for good measure and it's still an issue.

Edit: Still crashes as of https://github.com/AlpyneDreams/d8vk/commit/2e9e557bab77d027ae44efad1b657fa8135659a7

**Comment by AlpyneDreams** [comment]
Latest commit should fix this. Let me know if the game works.

**Comment by Blisto91** [comment]
Game is looking good now. Haven't found any issues in my short playtime
