### ISSUE TITLE
SW: Republic Commando crashes on game start when squad shadows are enabled

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#41]
![SWRepublicCommando](https://user-images.githubusercontent.com/6306593/197799761-164b6c67-cd34-4513-94b2-354b1e928c35.png)

The game plays the intro videos, but crashes right after clicking on Continue (it should proceed to the profile selection screen).

Unfortunately apitrace fails once again, in all possible combinations. I get a frame in the capture on game startup and it then crashes.

There's nothing of interest in the logs either, but I hope maybe @Blisto91 can capture a trace on windows. If not, I'll at least get a d3d9 trace with d3d8to9 again.

### Software information
SW: Republic Commando (UE2 title)

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.76
- Wine version: 7.19 Staging
- DXVK version: 1ee2743

### Apitrace file(s)
None, it crashes...

### Log files
- d3d8.log: [SWRepublicCommando_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/9861124/SWRepublicCommando_d3d8.log)
- d3d9.log: [SWRepublicCommando_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9861126/SWRepublicCommando_d3d9.log)

**Comment by WinterSnowfall** [comment]
[Here's a d3d9 trace I captured with DXVK](https://drive.google.com/file/d/1ZiNfM9lqhVFXNXXryQiOQ5iBuedp_Iba/view?usp=share_link). WineD3D is proving quite obstinate in 7.19 (windows resizing/virtual desktop memes I think), but I'm hoping this is somewhat fine.

**Comment by Blisto91** [comment]
I forgot to note it here also.
Wasn't able to get a d3d8 trace on windows. Game crashes

**Comment by Blisto91** [comment]
With latest master this now get further and you can play around in the main menu. 
Now it will instead crash upon loading a new game if you have turned on the graphics setting `SQUAD SHADOWS`

**Comment by AlpyneDreams** [comment]
See also: doitsujin/dxvk#1430

Does bump mapping work? Only squad shadows causes a crash?

**Comment by Blisto91** [comment]
Yes bump mapping (just via ingame setting) have not caused me any issues. squad shadows crash for me upon loading a game.
This on my R9 380

**Comment by Blisto91** [comment]
Game regressed with https://github.com/AlpyneDreams/d8vk/commit/25b4860f45a1b5f03b1044e9af5037a16589243b which makes it crash a bit after the game window appears.

[SWRepublicCommando_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9946758/SWRepublicCommando_d3d9.log)
d3d8 log is empty

**Comment by Blisto91** [comment]
I am now able to get to main menu again.

@WinterSnowfall Also figured why i was able to all along while he crashes. I had shader pre cache disabled in steam so there was no background video at the menu. If i enable it i also crash before i can select profile.

**Comment by AlpyneDreams** [comment]
> I am now able to get to main menu again.
> 
> @WinterSnowfall Also figured why i was able to all along while he crashes. I had shader pre cache disabled in steam so there was no background video at the menu. If i enable it i also crash before i can select profile.

Not sure how shader pre-cache would affect things, will have to look into it. Does turning off SQUAD SHADOWS still allow you to get past the main menu or has that regressed?

**Comment by Blisto91** [comment]
Yes without pre cache it works as before where i can play as long as squad shadows are off

**Comment by WinterSnowfall** [comment]
As of [6c1b0ed](https://github.com/AlpyneDreams/d8vk/commit/6c1b0ed6b1016afe130fe27856a28164900b8c22), I'm also able to play the game with squad shadows off, however one extra weird thing is that the usual menu background animations/videos aren't being shown, only a static background.

Here's the main menu with d3d8to9 + dxvk:
![MainMenuD3D8to9](https://user-images.githubusercontent.com/6306593/201413990-5b2f51c0-05d9-4da4-99e8-a7ac20ae6a3b.png)

And here's the menu with d8vk (same settings):
![MainMenuD8VK](https://user-images.githubusercontent.com/6306593/201414036-f9715735-482f-4993-a330-3d7cec6fa325.png)

**Comment by WinterSnowfall** [comment]
Not sure what fixed the background videos, but they are now playing as expected. The only remaining issue is with "Squad Shadows" - the game will crash on loading/starting a new game with the option enabled, but will work just fine otherwise.

**Comment by WinterSnowfall** [comment]
I haven't found a way to make d3d8 apitrace work, but I've captured two d3d9 traces using d3d8to9 and dxvk up to the point of the crash (should be just a few frames into starting a new game):
a) [One with Squad Shadows enabled](https://drive.google.com/file/d/18bw4lSwrKXIAIsbUjrrUOuIGc6jb2Z-b/view?usp=share_link)
b) [One with Squad Shadows disabled](https://drive.google.com/file/d/1gJZdLncF4FDUgLNTWzzCxE5iQodsg9jF/view?usp=share_link)

**Comment by mrdeathjr28** [comment]
Yeah confirm mainmenu are fixed in my case (cinematics works too)

![swrcfx](https://github.com/AlpyneDreams/d8vk/assets/6601480/11cb74d8-2834-4986-8f88-ce5a7444dd6d)
