### ISSUE TITLE
Upstream: D3D8 fixes that should be applied to D3D9 or DXSO too

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#44]
It's possible some of the fixes in d8vk are accounting for weird behavior in d9vk / dxso but not D3D9. There may be a couple of these as D3D9 also supports vs1.1 and ps1.4.

See #43 for one possible example. D3D9 docs state that replicate swizzle should be used but DXSO seems to allow arbitrary swizzles, which may either be fixing games or breaking them.

**Comment by AlpyneDreams** [comment]
#68 - AL16, R16, L16, AR16

**Comment by AlpyneDreams** [comment]
There's a possibility that equivalent functionality to f974535b7058ada89cb3de886ef9687de73610e0 (EndScene on Reset) might want to be added to d3d9 if that's how Microsoft d3d9 behaves.

Edit: Done with #204

**Comment by WinterSnowfall** [comment]
> There's a possibility that equivalent functionality to [f974535](https://github.com/AlpyneDreams/d8vk/commit/f974535b7058ada89cb3de886ef9687de73610e0) (EndScene on Reset) might want to be added to d3d9 if that's how Microsoft d3d9 behaves.

The trace included with https://github.com/doitsujin/dxvk/issues/2184 seems to suggest that is the case, albeit I expect most d3d9 games to behave properly and not rely on it.

**Comment by AlpyneDreams** [comment]
- [x] ~~b2b89ee0b8f99ed35c063ad3c69649f91a66f70f - [d3d9] Initialize m_mapFlags to 0~~
- [x] ~~4a7c627e3dc7d706916b870cd1e15f510c3951fd - [dxso] Implement bem instruction~~

**Comment by AlpyneDreams** [comment]
Since d8vk has been upstreamed and this issue is only tracking #43 and #68 now I can close it and just deal with those on their own.
