### ISSUE TITLE
Upstream: D3D8-related issues

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#45]
The following upstream issues may be relevant for us to investigate too:
- [x] [Silent Hill 2 Crash](https://github.com/doitsujin/dxvk/issues/1422) - using Enahanced Edition / d3d8to9
  - This occurs on Windows, but d9vk handles it just fine on Linux.

Using d3d8to9:
- [C&C Generals - d3d8to9](https://github.com/doitsujin/dxvk/issues/1498)
- [Blood Rayne - d3d8to](https://github.com/doitsujin/dxvk/issues/1828)
- [UT2004](https://github.com/doitsujin/dxvk/issues/2605) - issue occurs with d3d8to9 and d3d9

Other:
- [DXVK Marker Interfaces](https://github.com/doitsujin/dxvk/issues/1798)  - We technically add one of these.

See also: #44

**Comment by WinterSnowfall** [comment]
~Once https://github.com/doitsujin/dxvk/issues/3238 is fixed upstream, **Zwei: The Ilvard Insurrection** will also work properly with d8vk.~ Edit: We now have a config option in place that fixes it.

**Comment by shmerl** [comment]
Any plan to merge the project itself to upstream?

**Comment by Blisto91** [comment]
Maybe 🙂 

https://github.com/AlpyneDreams/d8vk/issues/16#issuecomment-1287826429

**Comment by shmerl** [comment]
May be a wrong place to ask, but why is the project building d3d9 - d3d11 DLLs in addition to d3d8 one? Is it just for reducing the need to customize build scripts or something else?

**Comment by Blisto91** [comment]
If the `build_d3d8.sh` script is used it should only be building d3d8 and d3d9 dll's. The reason for the d3d9 dll being included is that like d3d10 being implemented through the d3d11 parts upstream, here d3d8 is also implemented through the d3d9 parts. So d3d8 "goes through" the d3d9 code.
At the moment d8vk has to ship a custom version of `d3d9.dll` so upstream ones can't be used, but the goal is that that should be possible in the future. https://github.com/AlpyneDreams/d8vk/issues/19

**Comment by pchome** [comment]
I was curious and squash-merged d8vk with current dxvk master branch, minus scripts. Seems applied and work with 2.1 too.
[dxvk-d3d8-20230222.patch.txt](https://github.com/AlpyneDreams/d8vk/files/10809460/dxvk-d3d8-20230222.patch.txt)
Hope it not break too much on d3d9 side.

**Comment by AlpyneDreams** [comment]
There's a possibility that equivalent functionality to f974535b7058ada89cb3de886ef9687de73610e0 (EndScene on Reset) might want to be added to d3d9 if that's how Microsoft d3d9 behaves.

**Comment by AlpyneDreams** [comment]
> I was curious and squash-merged d8vk with current dxvk master branch, minus scripts. Seems applied and work with 2.1 too. [dxvk-d3d8-20230222.patch.txt](https://github.com/AlpyneDreams/d8vk/files/10809460/dxvk-d3d8-20230222.patch.txt) Hope it not break too much on d3d9 side.

Glad to hear it works. It shouldn't break anything, I have intentionally barely touched d3d9 since it's always changing upstream anyway.

**Comment by WinterSnowfall** [comment]
Some feedback from my tests.
 
>     * [C&C Generals - d3d8to9](https://github.com/doitsujin/dxvk/issues/1498)

~Still trying to get a hold of the game, to confirm this has been resolved.~ It works just fine now.

>     * [Blood Rayne - d3d8to](https://github.com/doitsujin/dxvk/issues/1828)

I have played through the first two levels maxed out @1080p 4x AA and it all seems fine. Cutscenes appear to limit the fps to 30, so maybe it is more of a perceived problem of d8vk/dxvk properly enabling vsync for the game?

Edit: There are some situations where the game slows down a bit, but that appears to be an engine limitation and not something we are doing wrong, as I can also see it in WineD3D.

>     * [UT2004](https://github.com/doitsujin/dxvk/issues/2605) - issue occurs with d3d8to9 and d3d9

Not a problem with d8vk in Wine at least, where you can use alb+tab without issues.
