### ISSUE TITLE
Max Payne 2

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#47]
- May or may not work with unmapping
- `LockRect` - Invalid Call - Rhedox
  - Locking a texture that's already locked. Perhaps we are returning the wrong tex/surf somewhere, or failing to unlock something.
- Likely not an issue: Render states 164 and 136 (see #46)

**Comment by AlpyneDreams** [comment]
An apitrace will make things a lot easier if possible! However I can look into trying the game myself at some point.

**Comment by Blisto91** [comment]
Will look into apitrace. Can't remember if I've tried or not.

The game indeed crashes for me unless i turn off unmapping.
There is also an issue where the text in the main menu is invisible. This is a regression as it didnt used to be the case. Haven't bisected yet or tried with the latest few commits

**Comment by Blisto91** [comment]
Now crashes during loading before main menu since https://github.com/AlpyneDreams/d8vk/commit/25b4860f45a1b5f03b1044e9af5037a16589243b

**Comment by Blisto91** [comment]
Now able to get to main menu. Tho text is still invisible so i need to look into that.

**Comment by AlpyneDreams** [comment]
I have fixed a couple tangentially related things however it still crashes. It seems the problem is not that we fail to unlock a texture, but that the program has an access violation (`0xc0000005`) and never gets to call UnlockRect.

**Comment by AlpyneDreams** [comment]
So presumably a bad pitch is being output and the game is writing out of bounds?

**Comment by AlpyneDreams** [comment]
> I have fixed a couple tangentially related things however it still crashes. It seems the problem is not that we fail to unlock a texture, but that the program has an access violation (`0xc0000005`) and never gets to call UnlockRect.

Can't reproduce this now. It's just locking a surface twice. Can't figure out why.

Tested on 7cccee1c471b04b04797ea02f228fb9f4f787fb3, with `d3d9.textureMemory = 0`, but no dice. This may be a vendor issue as I am on Intel.

**Comment by AlpyneDreams** [comment]
Tested on latest master (f8e1f46d623f4af4ea5dd84e332559bfe91392a0) on a different Intel GPU. No dice
