### ISSUE TITLE
First launch of D3D8 samples consistently crashes on MSVC

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#5]
Subsequent launches work.
This is a shader cache issue probably because renaming the exe will reproduce the issue.

[vertexblend1_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/6872797/vertexblend1_d3d9.log)

**Comment by dostup2055** [comment]
Hitman 2.
The game doesn't work. Black screen and "compiling shaders". (DXVK_HUD = full). 
Maybe there are problems with the video output? 

[hitman2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/6956623/hitman2_d3d9.log)

**Comment by AlpyneDreams** [comment]
Only occurs on MSVC

**Comment by AlpyneDreams** [comment]
> Hitman 2. The game doesn't work. Black screen and "compiling shaders". (DXVK_HUD = full). Maybe there are problems with the video output?
> 
> [hitman2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/6956623/hitman2_d3d9.log)

**Comment by AlpyneDreams** [comment]
Don't think this happens anymore.
