### ISSUE TITLE
Indiana Jones: Windowing bugs

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#50]
Indiana Jones and the Emperor's Tomb

"gameplay window area can move off center when alt tabbing" - Blisto

**Comment by Blisto91** [comment]
This seems to not directly be any d8vk commit that regressed but instead upstream commits pulled in a rebase.
I think i have found it to be the surface factory changes thats the culprit https://github.com/doitsujin/dxvk/compare/d8933ca...76e6b27

**Comment by Blisto91** [comment]
This is fixed with 1.0
