### ISSUE TITLE
[d3d8] - 18 Wheels of Steel Across America (514160) - Title fails to launch from it's launcher.

### ISSUE THREAD

**Issue by ZereoX** [AlpyneDreams/d8vk#53]
### Description:
**_18 Wheels of Steel Across America_** (514160) silently fails to launch after manually setting Direct3D on the launcher under "Gfx device". Upon pressing "Play !", title briefly opens a window and crashes.

### Software information
[18 Wheels of Steel: Across America](https://store.steampowered.com/app/514160/18_Wheels_of_Steel_Across_America/) (514160)

### System information
- GPU: Intel Iris Xe Graphics
- Driver: 31.0.101.3222
- Wine version: N/A (Windows 10 10.0.19044)
- DXVK version: [474d8c0](https://github.com/AlpyneDreams/d8vk/commit/474d8c0dd8baaba5b3a205c6a49d690e0b472d01)

### Apitrace file(s)
- Trace file did not playback, but including it in-case it helps: https://drive.google.com/file/d/1NmifqIb8D6dm4PrdBA5Xndz5H1xz3UFs/view?usp=share_link

### Log files
- d3d9.log: [prism3d_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10007906/prism3d_d3d9.log)

**Comment by WinterSnowfall** [comment]
FYI, I've tested the game with Wine and it works fine with the latest master. Apparently it's using the same engine (Prism3D) as **Duke Nukem: Manhattan Project**, so I'm hoping the above crash was fixed by #91 on Windows as well.

@ZereoX Could you please retest on Windows with latest master?

**Comment by ZereoX** [comment]
I can confirm this is working correctly on Windows with master ([2c56a1a](https://github.com/AlpyneDreams/d8vk/commit/2c56a1af7c0c8aee0da91e4cc49e4250c3fce7f9)).
