### ISSUE TITLE
[d3d8] - Acceleration of Suguri 2 (390710) - Title crashes on a white screen at launch.

### ISSUE THREAD

**Issue by ZereoX** [AlpyneDreams/d8vk#55]
### Description:
**_Acceleration of SUGURI 2_** (390710) title launches to a white screen and crashes shortly after instead of showing the developer and localization team logos.

| D8VK | Windows |
| ---- | ---- |
|<img width="641" alt="Acceleration of SUGURI 2 - D8VK" src="https://user-images.githubusercontent.com/761853/201794070-23499631-bea7-4cb6-90fc-a3a38c3ca954.png">|<img width="641" alt="Acceleration of SUGURI 2 - D3D8" src="https://user-images.githubusercontent.com/761853/201794041-3f03d40c-7da5-4486-884b-f21a4781ffbd.png">|

### Software information
[Acceleration of SUGURI 2](https://store.steampowered.com/app/390710/Acceleration_of_SUGURI_2/) (390710)

### System information
- GPU: Intel Iris Xe Graphics
- Driver: 31.0.101.3222
- Wine version: N/A (Windows 10 10.0.19044)
- DXVK version: [474d8c0](https://github.com/AlpyneDreams/d8vk/commit/474d8c0dd8baaba5b3a205c6a49d690e0b472d01)

### Apitrace file(s)
- Link: https://drive.google.com/file/d/1aEtGjldOIUhZrDHyK6E7D1Dq0JCRhzeU/view?usp=share_link

### Log files
- d3d9.log: [aos2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10007916/aos2_d3d9.log)

**Comment by WinterSnowfall** [comment]
@ZereoX I wanted to have a look over this and #54, and tried getting the traces you've shared (since I don't own the games), but they're not publicly accessible. Could you please make them public?

**Comment by ZereoX** [comment]
I can confirm this is working correctly on Windows with master ([2c56a1a](https://github.com/AlpyneDreams/d8vk/commit/2c56a1af7c0c8aee0da91e4cc49e4250c3fce7f9)).
