### ISSUE TITLE
[d3d8] - Advent Rising (3800) - Title silently fails to launch.

### ISSUE THREAD

**Issue by ZereoX** [AlpyneDreams/d8vk#56]
### Description:
**_Advent Rising_** (3800) title silently fails to launch.

### Software information
[Advent Rising](https://store.steampowered.com/app/3800/Advent_Rising/) (3800)

### System information
- GPU: Intel Iris Xe Graphics
- Driver: 31.0.101.3222
- Wine version: N/A (Windows 10 10.0.19044)
- DXVK version: [474d8c0](https://github.com/AlpyneDreams/d8vk/commit/474d8c0dd8baaba5b3a205c6a49d690e0b472d01)

### Apitrace file(s)
- Title silently fails to launch when attempting to trace.

### Log files
- d3d9.log: [advent_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10007977/advent_d3d9.log)

**Comment by AlpyneDreams** [comment]
~~Try manually placing the dlls next to the exe and running with `WINEDLLOVERRIDES=d3d8,d3d9=n,b`. Just checking to make sure it's not a Proton installation issue.~~

I see you're not on Wine. Interesting. I have heard this game does work on Linux. Weird that it's broken on Windows.

Try running with `DXVK_LOG_LEVEL=trace` and see if you get an `advent_d3d8.log` then.

**Comment by WinterSnowfall** [comment]
![AR2](https://user-images.githubusercontent.com/6306593/201927625-4041d200-aff3-4644-b02b-7e18d5e4d9c9.png)

Certainly does work with Wine, at least on Nvidia. Let me know if you want me to attempt a trace, although it being an UE2 title certainly doesn't get one's hopes up when it comes to capturing one.

**Comment by WinterSnowfall** [comment]
P.S.: Also works with Intel on Linux, FWIW.

![Advent_Intel](https://user-images.githubusercontent.com/6306593/211211577-97daa8c4-6195-4719-94de-c11ec3833c29.png)

**Comment by WinterSnowfall** [comment]
@ZereoX Hopefully this should work on Windows now as well, since d8vk has switched to statically linking d3d9. Can you please retest with latest main?

**Comment by ZereoX** [comment]
I can confirm this is working correctly on Windows with master ([2c56a1a](https://github.com/AlpyneDreams/d8vk/commit/2c56a1af7c0c8aee0da91e4cc49e4250c3fce7f9)).
