### ISSUE TITLE
BloodRayne crashes on startup

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#57]
The game crashes even before the intro videos are played. Luckily, I was able to get a trace this time.

### Software information
BloodRayne (Terminal Cut, but without using Ziggurat's d3d8.dll wrapper)

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.21 Staging
- DXVK version: 474d8c0

### Apitrace file(s)
[rayne1.trace.tar.xz](https://drive.google.com/file/d/1BuShmUQ7Bx78UOMwNJRBDcUlTXNGSbxl/view?usp=share_link)

### Log files
- d3d8.log: [rayne1_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10012874/rayne1_d3d8.log)
- d3d9.log: [rayne1_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10012875/rayne1_d3d9.log)

**Comment by Bitwolfies** [comment]
I'm curious, supposedly terminal cut relies on the wrapper for some of its enhanced features, would a properly working D8VK render those new features without the wrapper?

**Comment by WinterSnowfall** [comment]
> I'm curious, supposedly terminal cut relies on the wrapper for some of its enhanced features

I'm not sure what you're referring to. What are those "enhanced features"?. AFAIK aside from higher resolution textures (some with extra bump mapping here and there) and support for modern resolutions, there's nothing else. Not much if anything is changed in the original renderer and the wrapper is used for current and future compatibility with modern OSes. TL;DR the game isn't *magically* doing anything in the wrapper, it's still d3d8.

**Comment by Bitwolfies** [comment]
> > I'm curious, supposedly terminal cut relies on the wrapper for some of its enhanced features
> 
> I'm not sure what you're referring to. What are those "enhanced features"?. AFAIK aside from higher resolution textures (some with extra bump mapping here and there) and support for modern resolutions, there's nothing else. Not much if anything is changed in the original renderer and the wrapper is used for current and future compatibility with modern OSes. TL;DR the game isn't _magically_ doing anything in the wrapper, it's still d3d8.

That was my question for the most part, they bring up enhanced reflections among other improvements, wonder if any of it relies on dx9.

**Comment by WinterSnowfall** [comment]
> they bring up enhanced reflections among other improvements, wonder if any of it relies on dx9.

I don't know any more than what's in the press releases, but regarding these minor enhancements in particular, what I *think* happened was that they ported back some more advanced features that were already present in BR2 (also using d3d8), nothing more.

**Comment by WinterSnowfall** [comment]
~~#95 also gets the first title working, but as with BR2, the game will crash on exit.~~ (no longer the case with latest master)
