### ISSUE TITLE
Texture corruption in Empire Earth II

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#58]
![EE2](https://user-images.githubusercontent.com/6306593/202127502-25758e05-728a-42bc-9fb7-8d8cac2a55f9.png)

Some ground textures are corrupted, especially around buildings. I've captured a trace, which looks a lot worse than the actual game when played back, but spits out various warnings about **IDirect3DDevice8::CopyRects**, **IDirect3DTexture8::Release** and **IDirect3DDevice8::DeletePixelShader**.

Logs also spew out: `debug: CopyRects: Hit unhandled case from src pool 1 to dst pool 1`, so that's most likely the main issue I guess.

P.S.: The game looks fine with WineD3D and d3d8to + dxvk, of course.

### Software information
Empire Earth II

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.21 Staging
- DXVK version: 474d8c0

### Apitrace file(s)
[EE2.trace.tar.xz](https://drive.google.com/file/d/1ZgsqTOLqmFBToDmEnnNNlWSmtZugIMHJ/view?usp=share_link)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d8.log: [EE2_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10019562/EE2_d3d8.log)
- d3d9.log: [EE2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10019564/EE2_d3d9.log)

**Comment by AlpyneDreams** [comment]
The weird confetti should be fixed by 71c43afe8b2a4a5cfde0174a0f8f26f919bf278c.

Working on the apitrace warnings now. 

The DeletePixelShader ones should be fixed by my PR apitrace/apitrace#836, so update your apitrace :)

**Comment by WinterSnowfall** [comment]
> The weird confetti should be fixed by [71c43af](https://github.com/AlpyneDreams/d8vk/commit/71c43afe8b2a4a5cfde0174a0f8f26f919bf278c).

Looks like it is fixed, yes :+1: .

> Working on the apitrace warnings now.

Feel free to close the issue once you've dealt with everything. The game looks fine anyway, so I assume the rest of it is mostly harmless.

> The DeletePixelShader ones should be fixed by my PR [apitrace/apitrace#836](https://github.com/apitrace/apitrace/pull/836), so update your apitrace :)

Will do.

**Comment by AlpyneDreams** [comment]
The `IDirect3DTexture8::Release` problem should be fixed by f8e1f46d623f4af4ea5dd84e332559bfe91392a0. If any new issues arise make a new issue :)
