### ISSUE TITLE
Cossacks II: Battle For Europe - cursor issues

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#59]
The game is being obnoxious and force-loads the d3d8.dll in system32 regardless of overrides. ~~I was only able to capture a d3d9 trace using d3d8to9 because of that...~~ Edit: Nevermind, finally got a d3d8 trace.

It works well with d3d8to9 + dxvk, although it sometimes crashes with WineD3D, with the following error:
`Assertion failed: flags & WINED3D_MAP_NOOVERWRITE, file dlls/wined3d/cs.c, line 3042`

A second issue, that will become apparent after the crash is fixed is that the mouse cursor is invisible with d8vk or dxvk, but visible with WineD3D. ~~I'm assuming that's due to unimplemented support for software cursor in dxvk/d8vk.~~

### Software information
Cossacks II - Battle For Europe, GOG version

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.21 Staging
- DXVK version: 474d8c0 

### Apitrace file(s)
[engine.trace.tar.xz](https://drive.google.com/file/d/1j80UNi4gSKbzS5-R0tO7iwJ5SqNekxnF/view?usp=share_link)

### Log files
- d3d8.log: [engine_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10022854/engine_d3d8.log)
- d3d9.log: [engine_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10022857/engine_d3d9.log)

**Comment by WinterSnowfall** [comment]
The recent rebase makes this work and there appear to be no issues beyond a missing mouse cursor in the main menu. The cursor does show up if I alt+tab out and back in, so I'm trying to see if there's any workaround that fixes it entirely. I'll most likely close this issue after that.

**Comment by WinterSnowfall** [comment]
Turns out there more than one issue:
- cursor is not shown when landing on the main menu, as described above (WineD3D shows it)
- the game can't be played on anything but 1024x768, the resolution of the main menu; using anything else will cause a crash when staring a game ~~(since WineD3D crashes a few seconds into the main menu, I can't tell if it would work there)~~ (WineD3D now works, see trace above)

~~Unfortunately, I can't get a trace because of the reasons mentioned above, namely the game force-loading the d3d8.dll in system32, so it may be hard to debug.~~

**Comment by WinterSnowfall** [comment]
I managed to get a d3d8 trace with WineD3D today (thanks to @Riesi for teaching me a new apitrace trick). I've replaced the original link above. Replaying it with d8vk doesn't reproduce the crash unfortunately, but it occurs right after starting a new game when the swapchain is reset to the new size.

**Comment by WinterSnowfall** [comment]
[Here's a trace captured with d8vk](https://drive.google.com/file/d/10dIwcfEmhmtqrfB1F2TEiVEj3cxEDkOL/view?usp=sharing) up to the point of the crash. It looks fairly identical to WineD3D, so not sure what's going on. Apparently it crashes after a LockRect(), during a memcpy, so maybe it's running out of memory?

**Comment by WinterSnowfall** [comment]
Here's a new log with more details: [cossacks2.log](https://github.com/AlpyneDreams/d8vk/files/11950946/cossacks2.log)

Not sure why it wasn't capturing this bit before, but yes, the game is running out of memory. Also some CopyRect calls appear to fail when the game starts (may or may not be related to the crash at the end).

**Comment by WinterSnowfall** [comment]
The game was running out of memory because it was overusing state blocks (and we were not freeing them properly). That's been fixed now in #172 .

The cursor being invisible and not showing up until you alt+tab out and back in is still a problem. Seems to happen every time the window loses focus, such as when entering the main menu (from the load screen) and starting a new game (from the main menu).

**Comment by WinterSnowfall** [comment]
Regarding the invisible cursor issue, apparently the game is calling D3D8Device::ShowCursor(FALSE) right after recreating the swapchain, so we're sort of handling it right in theory... in practice we're obviously missing something, since the cursor should stay visible. WineD3D has the right behavior here, whatever that is.

If I hack D3D8Device::ShowCursor(BOOL) to always return FALSE (that's the previous state according to specs) and do nothing else, the cursor stays visible all the time, which is what seems to be proper behavior. Alternatively perhaps the game is expecting some windowing events to re-enable the cursor? Not entirely sure how to properly address this last bit...

**Comment by WinterSnowfall** [comment]
Should be fixed once the above PR is merged upstream and we rebase. The TLDR of it is we shouldn't mess with software cursors created using Win32, since dxvk doesn't implement software cursors. Some games simply call D3D8Device::ShowCursor(FALSE) out of the blue for some reason, which should be ignored in these cases.

**Comment by WinterSnowfall** [comment]
Now fixed upstream. We can close this issue once #172 is merged (that will address the crash) and we rebase (that will address the lingering cursor issues).

**Comment by 6b6279** [comment]
This might be off-topic, but I was wondering how you got Cossacks II to run normally at all. I can start the game with both with and without d8vk, but the game is extremely slow, to the point that basic cursor movements in the menu stutter and lag. Rebuilding from upstream fixed the issue with the mouse pointer. I couldn't play long enough to encounter a crash due to WineD3D, though, so I can't confirm if the game runs crash-free.

**Comment by WinterSnowfall** [comment]
> I was wondering how you got Cossacks II to run normally at all. I can start the game with both with and without d8vk, but the game is extremely slow, to the point that basic cursor movements in the menu stutter and lag.

Haven't done anything special to be honest, besides using Wine-Staging maybe, and I'm not seeing any slowdowns. I am globally enabling esync however, so perhaps that makes a difference in this game?

> I couldn't play long enough to encounter a crash due to WineD3D, though, so I can't confirm if the game runs crash-free.

Worked fine over here with d8vk and the PR mentioned above, played a couple of hour-long skirmishes.

**Comment by 6b6279** [comment]
Okay... do you get anything along the lines of `01e4:err:virtual:allocate_virtual_memory out of memory for allocation, base (nil) size 40000000` upon starting the game? I also have the GOG version of the game.

**Comment by WinterSnowfall** [comment]
> Okay... do you get anything along the lines of `01e4:err:virtual:allocate_virtual_memory out of memory for allocation, base (nil) size 40000000` upon starting the game? 

No, and I don't remember needing [to manually set the LAA flag](https://ntcore.com/?page_id=371) for this game in particular. But it might be taking up a bit too much address space in your case, I guess.

> I also have the GOG version of the game.

Same. But I have no issues with it really. WineD3D for instance always worked perfectly for me, even before I started looking into the issues d8vk had with the game.

**Comment by 6b6279** [comment]
I have tried applying the LAA patch (also tried launching the game both with and without WINE_LARGE_ADDRESS_AWARE) but with the patch the game crashes upon start with an assertion error (something about NValues and dynarray.h). I normally use the WoW64 build of Wine, but I have switched to Wine Staging, even re-initialized my prefix with WINEARCH=win32, enabled Esync globally (WINEESYNC=1). No luck. With Wine Staging I couldn't even get the game to start at all; the game crashed before the loading screen. I feel like the issue might be related to my graphics card. Forcing software rendering for the game with LIBGL_ALWAYS_SOFTWARE=1 (using wine-wow64) actually made the game slightly faster, although not fast enough to be playable. I am just really perplexed. There isn't a single review on WineHQ that mentions similar issues with the game, and the comments on ProtonDB seem to be mostly positive too, so I really comprehend why I can't get it to work.

**Comment by WinterSnowfall** [comment]
> (also tried launching the game both with and without WINE_LARGE_ADDRESS_AWARE) 

Note that doesn't do anything outside of Proton.

> even re-initialized my prefix with WINEARCH=win32

That's not really needed, I've always used win64 and it works just fine with the vast majority of games.

I'm not sure what more to suggest to be honest, as I'm not seeing any of the problems you're mentioning. But what I'd do as a first step is try to run the game (using the same prefix, maybe copied over) on different hardware. If you're getting the same issues, then it's Wine/prefix related, otherwise there may indeed be some hardware issue involved (although I find it unlikely).

P.S.: Also, if you're on Nvidia you need to make sure to install the 32-bit variant of `libnvidia-gl` or equivalent package, otherwise all your 32-bit games will silently crash (including native Linux games). I doubt this is the issue in your case, but mentioning it just in case, as it's a very common oversight with disastrous consequences.

**Comment by AlpyneDreams** [comment]
Should be fixed now. Open an issue in doitsujin/dxvk if not
