### ISSUE TITLE
Project Eden wonky fog (I think) and crash on game startup

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#60]
![PE](https://user-images.githubusercontent.com/6306593/202234415-e3e4c0de-40aa-4506-a903-bfc86b4d2662.png)

Apart from the blueness of the main menu, which should be dark and foggy, not blue, it also crashes during load when one attempts to start a new game.

I've captured a trace, but the issues aren't visible on replay. Not sure what may be the problem here...

### Software information
Project Eden

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.21 Staging
- DXVK version: 474d8c0 

### Apitrace file(s)
[Eden.trace.tar.xz](https://drive.google.com/file/d/1zS3LvTb2gWTAlsoxsRP8He1d47numbAH/view?usp=share_link)

### Log files
- d3d8.log: [Eden_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10023662/Eden_d3d8.log)
- d3d9.log: [Eden_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10023664/Eden_d3d9.log)

**Comment by AlpyneDreams** [comment]
Interesting, I am getting different results. Clearly it's not correct either way.

![image](https://user-images.githubusercontent.com/3376691/202656039-a81225cc-4481-4339-b085-516be68b7026.png)

**Comment by AlpyneDreams** [comment]
Can't get renderdoc to work on this craptop so this one might take a while to investigate.

**Comment by WinterSnowfall** [comment]
> Interesting, I am getting different results. Clearly it's not correct either way.

I'll trace it with d8vk, hopefully that will help. What you are seeing is in fact the correct way IIRC. It's how it looks like in WineD3D, in any case.

**Comment by WinterSnowfall** [comment]
Okay, so I got the weird blue fog to show in the trace now (guess I needed the latest master apitrace to capture things correctly). Unfortunately, the game crashed on load, as originally described, so the trace will end abruptly.

Here it is: [Eden_d8vk.trace.tar.xz](https://drive.google.com/file/d/1CBWYGzxN2-Qo_Q5jxoecl5OXayHRsyGJ/view?usp=share_link)

**Comment by r2rX** [comment]
> Okay, so I got the weird blue fog to show in the trace now (guess I needed the latest master apitrace to capture things correctly). Unfortunately, the game crashed on load, as originally described, so the trace will end abruptly.
> 
> Here it is: [Eden_d8vk.trace.tar.xz](https://drive.google.com/file/d/1CBWYGzxN2-Qo_Q5jxoecl5OXayHRsyGJ/view?usp=share_link)

Just F.Y.I, apitrace works with OpenGL, Direct3D and DirectDraw. To capture a Vulkan trace, use [renderdoc](https://github.com/baldurk/renderdoc).

**Comment by Blisto91** [comment]
@r2rX yes we know about both apitrace and renderdoc 🙂 
As posted above Alpyne has issues getting renderdoc to work.

**Comment by r2rX** [comment]
> @r2rX yes we know about both apitrace and renderdoc slightly_smiling_face As posted above Alpyne has issues getting renderdoc to work.

Seems I misunderstood. The apitrace was made using WineD3D. My bad. :)

**Comment by AlpyneDreams** [comment]
Okay the game is trying to CopyRects from ARGB to DXT, which isn't supported, and WineD3D doesn't let it, while d8vk does, presumably incorrectly. I wonder what happens on Windows d3d8 (does it work?) and if maybe the models are supposed to look a certain way that we've just never seen because of this lol.

If we could get a Windows apitrace, that'd be useful.

**Comment by AlpyneDreams** [comment]
Okay someone replayed the d8vk apitrace and indeed the game is just making invalid calls. I have pushed a commit to disallow this (abbe57f12fb4ec7a1a4efb04a31227231a1c6edb) in at least this specific case. @WinterSnowfall let me know if the game looks correct now or if there's still fog problems.

**Comment by WinterSnowfall** [comment]
![PE](https://user-images.githubusercontent.com/6306593/204141417-0766de74-ba5a-4265-a86d-1919f8ff1473.png)

Looks (what I always thought was) normal now with d8vk, fog problems gone, but attempting to start a new game still causes a crash.

**Comment by AlpyneDreams** [comment]
Great. I'll look into the crash.

**Comment by WinterSnowfall** [comment]
The crash seems to be caused by problems in CopyRects (multiple failures occur before the crash):

`debug: CopyRects: FAILED to copy from src pool 2 to dst pool 1`

**Comment by AlpyneDreams** [comment]
Seems like it's trying to copy from ARGB to DXT5. That probably should fail.

Is it possible to get a trace that reproduces this crash?

**Comment by WinterSnowfall** [comment]
Looks good with latest master :tada: . No more crashes when starting a new game.

![Eden](https://user-images.githubusercontent.com/6306593/222908340-01c9cd8f-7886-43cb-8caf-5ecae93c8324.png)
