### ISSUE TITLE
X2 - The Threat has some minor interface artifacts

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#61]
In-game menus (which in this particular game you will tend to use A LOT) show a square box around the first letter of the currently selected row and around text/section edges. This is not the case with WineD3D, which looks correct based on my many memories of playing the game in Windows.

Here's how it looks in WineD3D:
![Menu_WineD3D](https://user-images.githubusercontent.com/6306593/202252141-29ef33cf-5059-4bd1-a0ee-426601a57751.png)

Versus how it looks in d8vk:
![Menu_d8vk](https://user-images.githubusercontent.com/6306593/202252242-b3d9f7a8-fabf-4666-a722-78845a4d318f.png)

`debug: CopyRects: Hit unhandled case from src pool 1 to dst pool 1` get printed excessively in the logs.

### Software information
X2 - The Threat

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.21 Staging
- DXVK version: 474d8c0 

### Apitrace file(s)
[X2.trace.tar.xz](https://drive.google.com/file/d/1tsvATb03OtZ3c_OqCWbQnVaTzy-RDx-k/view?usp=share_link)

### Log files
- d3d8.log: [X2_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10024353/X2_d3d8.log)
- d3d9.log: [X2_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10024355/X2_d3d9.log)

**Comment by AlpyneDreams** [comment]
I've made some changes to CopyRects that should fix this (f2f6bc98110962eee8a93034b6707c43b7fe63d8). Try it out and let me know if it works!

**Comment by WinterSnowfall** [comment]
> Try it out and let me know if it works!

Still looks the same, unfortunately.

**Comment by WinterSnowfall** [comment]
![X2_new](https://user-images.githubusercontent.com/6306593/202692544-437f8d5a-096e-4ecd-aece-8ed03434b71f.png)

Well, actually it's not exactly the same... seems like some new elements have shown up, at least around the right column menu values, but they're still "smudged". See the screenshot.

**Comment by AlpyneDreams** [comment]
Oh now that's weird... It works for me, but I'll try a release build.
![image](https://user-images.githubusercontent.com/3376691/202717036-9015b9ab-ea5b-4ff1-b13e-6149af9dcd1d.png)

**Comment by AlpyneDreams** [comment]
Does the trace have the same issue for you?

**Comment by AlpyneDreams** [comment]
Looks like I may have fixed managed -> managed case, but the UpdateSurface failures are weird and I can't seem to reproduce them.

**Comment by AlpyneDreams** [comment]
Okay so something regressed probably in f2f6bc98110962eee8a93034b6707c43b7fe63d8 when I changed heuristics. Cracking this algorithm is tricky. May have to try snapping the rects to be block-aligned or go back to the old heuristic that somehow worked i have no idea how.

**Comment by WinterSnowfall** [comment]
> Okay so something regressed probably in [f2f6bc9](https://github.com/AlpyneDreams/d8vk/commit/f2f6bc98110962eee8a93034b6707c43b7fe63d8) when I changed heuristics.

Nope, game works with everything before b46bb74, so it's something in the most recent two commits that messed something up. I'm referring to it crashing in particular.

**Comment by AlpyneDreams** [comment]
> Nope, game works with everything before [b46bb74](https://github.com/AlpyneDreams/d8vk/commit/b46bb74fdfceb284168beefc0e8f49a84ca9d510), so it's something in the most recent two commits that messed something up. I'm referring to it crashing in particular.

Oh, interesting. Does it crash on b46bb74fdfceb284168beefc0e8f49a84ca9d510 or only f8e1f46d623f4af4ea5dd84e332559bfe91392a0?

**Comment by AlpyneDreams** [comment]
I've fixed the crash and I've pushed updated CopyRects code that should fix the interface artifacts. If any new issues are found, open a new issue :)

**Comment by WinterSnowfall** [comment]
These warnings:
```
warn:  D3D8WrappedObject::QueryInterface: Unknown interface query
warn:  b4211cfa-51b9-4a9f-ab78-db99b2bb678e
```
are still there, but otherwise the games works and looks perfect now. Thanks a lot for your work :+1: .
