### ISSUE TITLE
m_renderTarget caching causes crash in GTA: VC trace

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#64]
In the GTA Vice City trace file, and probably other places, caching the active rendertarget (b46bb74fdfceb284168beefc0e8f49a84ca9d510) causes an access violation.

It has been reverted for now (0c563be398d40e1dbe0348f95a326a31194f45bb) while this issue is open.

**Comment by WinterSnowfall** [comment]
Oh, so you had an issue open for it, missed that :)... in that case I'll add more detail here as well.

Other games that have issues with it: [Curse - The Eye of Isis](https://github.com/AlpyneDreams/d8vk/issues/75#issuecomment-1419626292)

Games that seem to need the ref: #98 #102

**Comment by AlpyneDreams** [comment]
Good news! This was fixed yesterday by 567b0335bdc55e201b0cab825845f4e3ea75b0f1!

It's also worth noting that sometimes this would crash in CreateTexture instead of SetRenderTarget, and I don't know why it was doing that. However this doesn't happen after 567b0335bdc55e201b0cab825845f4e3ea75b0f1 so I will not worry about that for now.
