### ISSUE TITLE
Add support for NVIDIA Shadow Buffers

### ISSUE THREAD

**Issue by flibitijibibo** [AlpyneDreams/d8vk#65]
Shadow buffers were a feature found in GeForce4 Ti hardware, and then sort of vanished soon afterward:

https://www.nvidia.com/en-us/drivers/feature-shadowbuffers/

This is a feature primarily seen in two D3D8 games: [Splinter Cell](https://store.steampowered.com/app/13560/Tom_Clancys_Splinter_Cell/) and Splinter Cell: Pandora Tomorrow (mysteriously not on Steam):

https://www.pcgamingwiki.com/wiki/Tom_Clancy%27s_Splinter_Cell#/media/File:Splinter_Cell_shadow_fix_comparison.png

The only modern implementation I'm aware of is dgVoodoo2, which is proprietary, so I don't have much information beyond the above!

**Comment by AlpyneDreams** [comment]
Are there any screenshots or footage of the game running on original hardware?

**Comment by flibitijibibo** [comment]
Took a quick look around and this post has a few comparison shots: https://ancientelectronics.wordpress.com/2017/08/02/splinter-cell-pc/

Searching combinations of "splinter cell shadow buffers geforce4" gets some results, YMMV.

**Comment by AlpyneDreams** [comment]
Also found some speculation here: https://forum.beyond3d.com/threads/explain-please-shadow-buffers.17504/

Nothing definitive yet, but I'm trying out the game now.

**Comment by AlpyneDreams** [comment]
After testing the game, I can confirm that there are no shadows where there should be.

**Comment by AlpyneDreams** [comment]
Can also confirm we get results with projector shadows but not shadow buffers. Hmm.

![20221127081556_1](https://user-images.githubusercontent.com/3376691/204145589-84a9648b-8a1a-4624-b36b-55d2a17d337d.jpg)

**Comment by AlpyneDreams** [comment]
Looking at RenderDoc. Seems like in buffer mode it's sampling a D24S8 texture and using the returned alpha (w) as the shadow value. But we are just getting full white from modern GPUs.

Shadows are drawn as quads overlaid onto surfaces they hit and the volumetrics are a separate draw call and also sample the shadow buffer.

I've also captured it on dgVoodoo2 to see what that does.

![image](https://user-images.githubusercontent.com/3376691/204150988-53d6d307-a595-4f34-98e9-f93ca9b6507c.png)

Here's the shader that draws shadows on the wall:

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/3376691/204149537-16359ea4-dc83-4977-9dcb-080e990e6ba7.png)
</details>

Here is what ps_main is doing: (this code is roughly equivalent to the above):

<details>
<summary>GLSL</summary>

```glsl
void ps_main()
{
    // r3 = color0
    r3 = shader_in[2];
    
// this is the actual shadow sample itself //

    // get texcoords at shader_in[5] and multiply z by some amount
    r1 = shader_in[5];
    r1.z = r1.z * cb3.m[14].z;

    // get sample at (-1, 0)
    vec4 _77 = r4;
    _77.x = textureOffset(sampler2DShadow(t0, s0), vec3(r1.xy, r1.z), ivec2(-1, 0));
    r4 = _77;
    
    // get sample at (1, 0)
    vec4 _89 = r4;
    _89.y = textureOffset(sampler2DShadow(t0, s0), vec3(r1.xy, r1.z), ivec2(1, 0));
    r4 = _89;
    
    // get sample at (0, -1)
    vec4 _100 = r4;
    _100.z = textureOffset(sampler2DShadow(t0, s0), vec3(r1.xy, r1.z), ivec2(0, -1));
    r4 = _100;
    
    // get sample at (0, 1)
    vec4 _111 = r4;
    _111.w = textureOffset(sampler2DShadow(t0, s0), vec3(r1.xy, r1.z), ivec2(0, 1));
    r4 = _111;


    // get final sample at (0, 0)
    r1 = vec4(texture(sampler2DShadow(t0, s0), vec3(r1.xy, r1.z)));

    // dot the 4 neighbor samples together with some kind of hack?
    vec4 _128 = r4;
    _128.x = dot(r4, uintBitsToFloat(uvec4(1045220557u)));
    r4 = _128;
    
    // repeat hack for r1
    r1 = fma(r1, uintBitsToFloat(uvec4(1045220557u)), r4.xxxx);

    // set a constant w, (why?)
    vec4 _137 = r1;
    _137.w = uintBitsToFloat(1065353216u);
    r1 = _137;

    // r2 - shadow shape mask, comes from t1, just a white texture, clamped
    r2 = texture(sampler2D(t1, s1), shader_in[6].xy);
    
    // r1 is shadow data (multiply by r3 to see it)
    // r2 is the mask for the whole area
    // r3 is the shadow intensity (shader_in[2]) i.e. color0
    // r1 * r2 is full intensity shadow
    // r1 * r2 * r3 is the final output
    r0 = r1 * r2;
    r0 *= r3;
    o0 = r0; // final output
}
```
</details>


Obviously, actual NVIDIA hardware may not do exactly this, but it seems like it's pretty close. It looks like bilinear filtering of 1/0 values to get bilinear 2x2 PCF which seems to have been a standard feature and done in one fetch according to [this presentation](https://developer.download.nvidia.com/presentations/2008/GDC/GDC08_SoftShadowMapping.pdf).

It looks like this might be similar to the hack that's [documented by Aras here](https://aras-p.info/texts/D3D9GPUHacks.html#shadowmap).

**Comment by AlpyneDreams** [comment]
In d8vk the VS is passing really big z values into texcoord 0, like 300,000. So that's why we're getting white from the shadow texture.

But in dgVoodoo, the z is multiplied by `cb3.m[14].z` to get what I assume is NDC depth, which is around `5e-8` and indeed reusing that magic number produces somewhat workable results. I believe it's a component of the projection matrix, but I can't find an equivalent in the constants being passed to either our VS or PS shader. Can probably work something out with `gl_FragDepth` or something.

Also I think the xy of the texcoord is still wrong too somehow even after fixing the z.

Edit: Actually [this video](https://youtu.be/WZ9rL5nbn84?t=794) shows a different position for the shadows that looks correct to me.

**Comment by AlpyneDreams** [comment]
I have found the best documentation of this feature [here](http://gamma.cs.unc.edu/SIG03_COURSE/SIGCOURSE-11.pdf) (see "Hardware Shadow Mapping"). Additional info in [these slides](http://vis.eng.uci.edu/courses/ece104/current/todo/tmp/slides/nvidia_shadow_mapping_1spp.pdf).

**Comment by AlpyneDreams** [comment]
The hack dgVoodoo 2 is using with the `uintBitsToFloat` is simply to divide the 5 samples by `0.25` and set w to `1.0`. This is like a [2x2 PCF](http://jojendersie.de/wp-content/uploads/2013/06/PCF.png).

Now I'm not sure if we should use `OpImageDrefGather` and try to emulate this behavior or if dgVoodoo is just showing off. I suspect hardware at the time couldn't manage 5 bilinear samples per texel very easily. We already get bilinear PCF from `sampler2DShadow`. But it's possible it was a feature. NVIDIA just calls it a "proprietary shadow-filtering algorithm" on their website lol.

**Comment by AlpyneDreams** [comment]
`OpImageDrefGather` doesn't provide bilinear filtering so it doesn't look that great. I've gone ahead and implemented a 2x2 PCF just using 4 regular bilinear taps.

**Comment by mirh** [comment]
You should check the thread with the original fix for more info, traces and even code examples..
https://www.vogons.org/viewtopic.php?f=8&t=41443&start=60

**Comment by HenrikHolst** [comment]
Exactly how is this enabled in the game? If I put v1.0 of d3d8.dll in the Splinter Cell/system/ folder and also put a dxvk.conf there with "d3d8.useShadowBuffers = True" and set (or completely comment out) "ForceShadowMode=1" in SplinterCell.ini then I get no shadows at all in the first level where Lambert walks across the corridor and he is supposed to leave a shadow at the wall.

I have set "dxvk.hud = 1" to see that d8vk is loaded.

**Comment by AlpyneDreams** [comment]
> You should check the thread with the original fix for more info, traces and even code examples.. https://www.vogons.org/viewtopic.php?f=8&t=41443&start=60

Thanks, this is useful!

Specifically:
http://www.jiri-dvorak.cz/scellpt/
http://web.archive.org/web/20070104115249/http://www.nvidia.com/object/General_FAQ.html#G5

**Comment by donizettilorenzo** [comment]
dgVoodoo2 now is on github: https://github.com/dege-diosg/dgVoodoo2

**Comment by HenrikHolst** [comment]
> dgVoodoo2 now is on github: https://github.com/dege-diosg/dgVoodoo2

Looks to be only the binary and some examples though and not the source?

**Comment by mirh** [comment]
I'm too pleb to follow [engineers](https://web.archive.org/web/20110323222029/http://developer.nvidia.com/forums/index.php?=&showtopic=34) [discussing](https://web.archive.org/web/20080503032425/http://rage3d.com/board/showthread.php?s=02ef517d5efee4094aeef8e61006739f&t=33921102&page=11#post1335433365) [filtering](https://forum.beyond3d.com/threads/explain-please-shadow-buffers.17504/) (also higher qualities are noted in the [SC readme](https://youtu.be/sXWHaADTKk4?t=162), and [here](https://download.nvidia.com/developer/GPU_Gems/Sample_Chapters/PSMs_Care_and_Feeding.pdf#page=21)) but nvidia did have some kind of [extended description](https://web.archive.org/web/20030614095009/http://nvidia.com/docs/lo/1047/SUPP/Shadow_Buffer_100101.pdf) for it:

> Once a shadow map is created and stored in the shadow buffer, it is ready to be used. When the GeForce3 Ti GPU renders the scene, it performs the following steps:
>1. Transform the pixel into the coordinate system defined by the light source.
>2. Use the texture filtering techniques to read multiple Z-values stored in the shadow buffer from locations that surround the XY location of the pixel. The multiple Z-values are used for two important calculations:
>    * a) Using a proprietary shadow algorithm, the multiple Z-values are compared to the single Z-value for the pixel to determine what fraction of the pixel is in shadow. This enables up to 256 discrete levels of shadow to create soft edges for shadows.
>    * b) Using texture-filtering algorithms, the multiple Z-values are filtered down to a single Z value.
>3. The results of steps 2a and 2b are used by the nfiniteFX engine as input data for pixel shading operations. If the Z value of the pixel is equal to (or very close to equal to) the Z value stored in the shadow buffer, then the pixel is lit. Otherwise, the pixel is shadowed with the degree of shadow determined by the result of step 2a. The nfiniteFX engine can also turn off specular highlights for any pixel that is in shadow, enhancing the realism of the image.

> **Soften shadow edges**: Shadow mapping can soften shadow edges using the proprietary shadow-filtering algorithm with up to 256 discrete levels of shadowing based on the percentage coverage of the pixel, if the pixel area is partially shadowed and partially lighted.
