### ISSUE TITLE
A.I.M. and A.I.M. 2: Clan Wars - Glitched 2D world map

### ISSUE THREAD

**Issue by ghost** [AlpyneDreams/d8vk#70]
Both A.I.M.: Artificial Intelligence Machines and A.I.M. 2: Clan Wars (and A.I.M: Racing, too!) work flawlessly, except that the former two have few problems with map mask of explored areas, one of which this issue covers.

The 2D world map used to briefly work correctly about a month ago but I've since lost track of the commit, after the codebase was updated to newer DXVK, that added/fixed its requirements in the first place. First, after breaking, it stopped drawing map texture altogether and instead just showed empty mask while now the texture is back but this time it's _"striped"_.
For comparison, the issue doesn't exist neither with WineD3D nor d3d8to9 + DXVK.

| D8VK  | d3d8to9 + DXVK |
| ------------- | ------------- |
| ![M1_D8VK](https://user-images.githubusercontent.com/27519308/205216792-c5dcde44-8bc4-44a6-8350-d2b8b065ab9d.png)  | ![M1_d3d8to9+DXVK](https://user-images.githubusercontent.com/27519308/205216794-56aeeeb4-bbac-474d-ad0a-a7b81da12c2d.png)  |

P.S. I mention here both affected games in the same issue as they use the same (but slightly altered) engine and are in overall very similar.

### Software information
- A.I.M.: Artificial Intelligence Machines, version 1.06
- A.I.M. 2: Clan Wars, version 1.3.25

### System information
- GPU: AMD Radeon RX 5700 XT
- Driver: Mesa RADV (free) 22.2.3
- Wine version: 7.22 Staging
- DXVK version: 1feb1be480effabd48b901d3b6023048d036cfb9

### Apitrace file(s)
- [AIM.v1.06.trace](https://www.mediafire.com/file/zd9wk685xelxcwl)
- [AIMII.v1.3.25.trace](https://www.mediafire.com/file/jvh2pyj00m8s0el)

### Log files
- [AIM_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10138187/AIM_d3d9.log)
- [AIMII_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10138185/AIMII_d3d9.log)

**Comment by AlpyneDreams** [comment]
Can you capture a D3D8 apitrace? These are D3D9 apitraces.

**Comment by AlpyneDreams** [comment]
Nevermind, I found the game for like $3 and recorded one myself. Working on a fix now.

**Comment by AlpyneDreams** [comment]
Fixed in c6708fadf471415fb4de81d477c9839fe938e663. Open a new issue if there's any more trouble with this game.

**Comment by ghost** [comment]
Thank you!

> Can you capture a D3D8 apitrace? These are D3D9 apitraces.

Sorry! Will keep it in mind for the next time.
