### ISSUE TITLE
 A.I.M.: Artificial Intelligence Machines - Colored or partially invisible models in menus

### ISSUE THREAD

**Issue by ghost** [AlpyneDreams/d8vk#74]
1. Most of the time models that are displayed in menus (gliders, weapons and other equipment) appear in a single unshaded color. Sometimes, in rare cases, they appear as normal.
The color of models is the same as current color of sky or fog in world. It can be easily manipulated and confirmed by running v1.06 of A.I.M. with `-freecamera` argument and, while in world, pressing 'N' key to speed up time and change color of sky/fog. Both colors will be the same.

![AIM v1 06 colored](https://user-images.githubusercontent.com/27519308/206062894-e703f1b9-7634-40ef-bce1-abc940515d37.png)

2. Models made up of multiple parts (like buildings) that are displayed in HTML-like "iframe" are sometimes missing some of their parts. They seem to be transparent/half-transparent rather than actually missing since the contour itself is still there.

![M1 InvisibleParts](https://user-images.githubusercontent.com/27519308/206065076-68728484-c100-4ed1-8042-cfd9f45ebdeb.png)

NB! Neither is actually D8VK's fault at all, but rather seems to be related to version 1.06's big changes as I haven't encountered something like this in any other version (except pre-release v0.21 in which the whole UI was colored. It's a lot rarer in v0.21 and couldn't reproduce it this time unfortunately).
I've experienced these issues also on Windows without any compatibility layers (other than those what MS and/or driver vendors include for d3d8). I'm hoping D8VK could implement a 'hotfix' of some sort specifically for A.I.M. 1, if possible.

### Software information
- A.I.M.: Artificial Intelligence Machines, version 1.06

### System information
- GPU: AMD Radeon RX 5700 XT
- Driver: Mesa RADV 22.3.0
- Wine version: 7.22 Staging
- DXVK version: a50de4619a80191d208d73b42c7cc2a10fb4b9e2

### Apitrace file(s)
- [AIM.v1.06.color.trace](https://www.mediafire.com/file/p57aq3viw9g9ql1)

### Log files
- [AIM_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10171803/AIM_d3d9.log)

**Comment by AlpyneDreams** [comment]
Seems like the game is giving a really large `D3DRS_FOGSTART`, much much larger than FOGEND. As for the iframes, they're just rendering with that alpha into the rendertarget. It's definitely exclusive to 1.06, my version of the game doesn't have it.

I could potentially look into implementing a workaround at some point, but everything seems to be working as intended here.

**Comment by ghost** [comment]
> As for the iframes, they're just rendering with that alpha into the rendertarget. It's definitely exclusive to 1.06, my version of the game doesn't have it.

What version of the game do you have (it's listed in the metadata)? I'm able to reproduce this behaviour on both of the other two DRM-free versions that I know of and can launch (1.02a AKA 1.0.1.0 and 1.03 AKA 1.0.3.1).
For some reason only certain building models are affected. I've uploaded a saved game that is located in one of the game bases which's models is affected by it, see how it appears for you. Place the file in `%gamerootdir%\SAVES\`. In-game menu it'll be called simply "iframe".

[MM_9.sav](https://www.mediafire.com/file/8t3tiqn0n998fer)

> I could potentially look into implementing a workaround at some point, but everything seems to be working as intended here.

That would be great! I hope in time there will emerge a game/version-specific workaround for this.

**Comment by GranMinigun** [comment]
> seems to be related to version 1.06's big changes

Can confirm this happening in Russian retail version patched to 1.04 + 1.06 (it's supposed to just remove StarForce protection, if I recall). Definitely remember it happened on GeForce GT 610M and Windows 7, but can't remember if it was a problem on Radeon HD 5750 and Windows XP/7.

> except pre-release v0.21 in which the whole UI was colored

Was the case in the initial retail release as well, and it happened to me much more often than I'd like it to. Happy times. Was fixed in the first patch (1.02a).

Anyway. Wouldn't it make more sense to ask someone like Silence if they'd be interested in patching the game?

**Comment by ghost** [comment]
> Can confirm this happening in Russian retail version patched to 1.04 + 1.06 (it's supposed to just remove StarForce protection, if I recall).

To my knowledge v1.06 did more than that. I remember something being said it to have introduced some sort of compatibility changes for Windows Vista/7, although I never found an official changelog so I don't know for sure (hence enter the colorful models in menus; never seen it in 1.03, for example).
To name a few gameplay changes, in v1.06 contour fields started to inflict damage, and NPCs were temporarily hidden in certain radius while leaving building (neither was mentions in v1.04 changelog). It's also possible the variable FOV was removed in this version.

> Definitely remember it happened on GeForce GT 610M and Windows 7, but can't remember if it was a problem on Radeon HD 5750 and Windows XP/7.

Do you mean both issues, the "_iframe_" one, too?

> Was the case in the initial retail release as well, and it happened to me much more often than I'd like it to. Happy times. Was fixed in the first patch (1.02a).

Oh, I see. It's the 3rd item in the v1.02 changelog, right?

> > patch v.1.02 from 03/16/2004
> > [...]
> > 3. Fixed UI painting on systems with Radeon 8500-9200.

I never had a chance to play any of the DRM-protected versions, besides v1.03, so v0.21 was the first version I learned of this bug. Didn't make any sense to me at the time I read it.

> Anyway. Wouldn't it make more sense to ask someone like Silence if they'd be interested in patching the game?

Sorry, who? But yes, I suppose you're right. Both are purely game issues after all, and not caused by D8VK.

Closing.

**Comment by GranMinigun** [comment]
> in v1.06 contour fields started to inflict damage

1.04, 32nd changelog item reads "Force field now deals damage on approach" (or something like that).

> NPCs were temporarily hidden in certain radius while leaving building

Do you mean they're greyed out on the radar? My memory is rusty, but weren't they always passive and grey within building's safe area?

In any case, if there were any additional changes in 1.06, then they likely were only mentioned on the game's forum, unless someone did a research and documented everything.

> Do you mean both issues, the "_iframe_" one, too?

Now that you ask, yeah, although I can't tell if it happened to me in the release version.

> Oh, I see. It's the 3rd item in the v1.02 changelog, right?

Correct. I had an ATi Radeon X1650 back then.

> Sorry, who?

AKA CookiePLMonster ([click](https://cookieplmonster.github.io/)). He does patches for older games from time to time, might be worth it to ask him about A.I.M..
