### ISSUE TITLE
D3D8 games reported to work mega-"issue"

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#75]
Not a bug - but since you can't PR against Wikis on GitHub, and just so that I don't forget about anything, I'm opening this "issue" to keep track of games which are known to work but are not yet mentioned in the Wiki.

I'll scratch these off whenever they're added, but for now I've tested/played:

- [x] Rise of Nations
- [x] Delta Force - Black Hawk Down
- [x] Enclave
- [x] Mobile Forces
- [x] Judge Dredd - Dredd vs Death
- [x] Red Faction II
- [x] Star Trek - Armada II
- [x] Tony Hawk's Pro Skater 3

None of the above show any issues as of 0.10 at least.

**Comment by AlpyneDreams** [comment]
Added all of these to the wiki. Thank you for testing 'em!

**Comment by WinterSnowfall** [comment]
@AlpyneDreams I've gone through all the d3d8 games I currently own and can confirm a few more working titles:

- [x] Broken Sword 3: The Sleeping Dragon
- [x] Freedom Force
- [x] Hidden And Dangerous 2
- [x] KnightShift (aka Polanie 2)
- [x] RC Cars
- [x] Sam And Max - Beyond Time And Space
- [x] Sherlock Holmes - Secret of the Silver Earring
- [x] Still Life
- [x] Star Wars: Starfighter
- [x] The Guild (aka Europa 1400)
- [x] Thief - Deadly Shadows (apparently an UE2 game)
- [x] Uru - Complete Chronicles

There are also a bunch of new bugs I will raise once I collect all the traces and maybe figure some stuff out about what is causing them.

**Comment by AlpyneDreams** [comment]
If Sam & Max: Beyond Time And Space works, does that mean that Sam & Max Save the World works too?

**Comment by AlpyneDreams** [comment]
Thief Deadly Shadows uses the same everything as Deus Ex 2 so I'm not surprised.

**Comment by WinterSnowfall** [comment]
> If Sam & Max: Beyond Time And Space works, does that mean that Sam & Max Save the World works too?

I believe the original version of it should, but at some point it got updated to d3d9, while Sam & Max: Beyond Time And Space remained on d3d8. At least on GOG. So couldn't really confirm it.

**Comment by AlpyneDreams** [comment]
> I believe the original version of it should, but at some point it got updated to d3d9, while Sam & Max: Beyond Time And Space remained on d3d8. At least on GOG. So couldn't really confirm it.


Hmm interesting. They re-released them in d3d11 recently. I used to have the original version somewhere.

**Comment by AlpyneDreams** [comment]
I have added all these to the wiki. I'll leave this issue open so people can easily report working games :)

**Comment by WinterSnowfall** [comment]
@AlpyneDreams Due to @Blisto91's boundless generosity, I've tested a new batch of d3d8 titles I had yet to purchase, but now own and have added to my grand d3d8 games Wine prefix (it's sitting at ~85 d3d8 titles atm). Here are some more confirmed to work without any issues on Linux:

- [x] 18 Wheels of Steel: Across America
- [x] 18 Wheels of Steel: Hard Truck
- [x] Another World (15th Anniversary Edition)
- [x] Chaser
- [x] Conflict: Desert Storm
- [x] Freedom Fighters
- [x] Guilty Gear Isuka
- [x] Guilty Gear X2 Reload
- [x] I.G.I. 2: Covert Strike
- [x] Lords of the Realm III
- [x] MegaRace 3
- [x] Moto Racer 3
- [x] No One Lives Forever 2: A Spy in H.A.R.M.'s Way (tested using the v1.2 demo)
- [x] Rhiannon - Curse of the Four Branches
- [x] Silent Hill 4: The Room
- [x] Ys VI - The Ark of Napishtim

**Comment by Chiitoo** [comment]
Had a quick run with the d3d8 title:

- Final Fantasy XI Online

Things seem to work as far as I tested, though performance-wise things seemed similar to built-in (only issue I noticed, was the mouse cursor kind of glitching in and out of existence a bit, but not sure if the HUD could have caused that?).

Thank you for working on this interesting project!

**Comment by WinterSnowfall** [comment]
I'll mention this separately, because it's a special case. 

- Curse: The Eye of Isis

Works fine on current master (f4988e7) - however crashes when starting a new game if reffing here, similarly to GTA Vice City:

```
        // FIXME: Doing this crashes a GTA Vice City trace
        // and possibly other things too. Investigate.
        //m_renderTarget = ref(surf);
```
Since there are other games that apparently depend on this being in place, the situation is rather problematic.

P.S.: Here's a trace of the game, should it ever prove useful: [Curse.trace.tar.xz](https://drive.google.com/file/d/1aT2KljzYntUMObORrWeIE57_gJPcffcR/view?usp=share_link)

**Comment by Michal-Szczepaniak** [comment]
So in Duke Nukem: Manhattan Project, after compiling master d8vk, double jump doesn't work anymore.

EDIT: Solution is to limit fps, i used DXVK_FRAME_RATE=60

**Comment by WinterSnowfall** [comment]
> EDIT: Solution is to limit fps, i used DXVK_FRAME_RATE=60

Just FYI, the game also has a builtin refresh rate limiter you can enable in its launcher, if you go to "Advanced".

Edit: Huh, that doesn't always limit the refresh rate properly... *sigh*. Well, whatever works :).

**Comment by Michal-Szczepaniak** [comment]
lol there's no advanced settings xd

**Comment by WinterSnowfall** [comment]
> lol there's no advanced settings xd

... apparently the Steam version doesn't have the [classic launcher](https://www.pcgamingwiki.com/wiki/Duke_Nukem:_Manhattan_Project#/media/File:Duke_Nukem_Manhattan_Project_launcher.png). Nevermind then :).

**Comment by Michal-Szczepaniak** [comment]
ok i'm back after extensive testing and the issue is real. I've tried limiting fps in game and via the `DXVK_FRAME_RATE` while both help, they don't eliminate the issue. Sometimes key is not registered at all and i can hold it for like 3 seconds before it gets registered. Issue is not present on wined3d or opengl

**Comment by WinterSnowfall** [comment]
@Michal-Szczepaniak Please open a separate issue for it and let's discuss it there.

**Comment by Michal-Szczepaniak** [comment]
Oki on it

**Comment by AlpyneDreams** [comment]
> Curse: The Eye of Isis

Reported to work now.

**Comment by AlpyneDreams** [comment]
Added all the new ones including Curse and Final Fantasy XI

**Comment by WinterSnowfall** [comment]
@AlpyneDreams The following titles can be added to the "Working on Linux, but with notable bugs" section, since they work fine except for the problems mentioned below:
- [x] Cossacks II: Battle For Europe (hidden mouse on main menu and crash on resolution change)
- [ ] Hitman 2: Silent Assassin (crash on new game after changing graphics options)
- [ ] Incoming Forces (broken geometry during some cutscenes, but seems to be game-specific)
- [ ] Soldiers: Heroes of World War II (videos flickering on playback)
- [ ] Star Wars: Republic Commando (crashes with Squad Shadows enabled)

**Comment by WinterSnowfall** [comment]
I've also tested a couple of additional titles and confirmed they are working without issues:
- [x] Desert Thunder
- [x] Blitzkrieg Anthology

**Comment by jr1991-g** [comment]
I've tested the only game I'm interested and it works better than Windows, with kitserver mods enabled. No graphical glitches and no crashes so far. Tested on pure wine, 32 and 64 prefixes.

- [x] Pro Evolution Soccer 6

**Comment by WinterSnowfall** [comment]
- [x] Apache AH-64 Air Assault
- [x] BloodRayne
- [x] BloodRayne 2
- [x] BlowOut
- [x] Commandos 3
- [x] FireStarter
- [x] Haegemonia: Legions of Iron
- [x] Haegemonia: The Solon Heritage
- [x] Hitman: Contracts
- [x] Inquisitor
- [x] Iron Storm
- [x] Nosferatu: The Wrath of Malachi
- [x] Project Eden
- [x] Pure Pinball 2.0 Redux
- [x] Railroad Tycoon 3
- [x] Rayman 3 (with [Better Rayman 3](https://raymanpc.com/forum/viewtopic.php?p=992390&sid=a7a0f8f8607aa1ec50bf95b0c6d59919#p992390))
- [x] Restaurant Empire
- [x] Smash Up Derby
- [x] Supreme Ruler 2010
- [x] Supreme Ruler 2020 Gold
- [x] Warcraft III (+ Frozen Throne, up to patch 1.26a)
- [x] Warrior Kings
- [x] Warrior Kings: Battles

the above games that had open issues are now working. Here are also some new games that were tested and confirmed to work:

- [x] Battlefield 1942 (& Addons), according to @Blisto91 
- [x] Command & Conquer: Generals (+ Zero Hour)
- [x] Desert Law
- [x] FATE
- [x] Hover Ace
- [x] Let's Ride: Silver Buckle Stables
- [x] Metal Gear (MSX 2 emulated version)
- [x] The Moment of Silence

**Comment by mrdeathjr28** [comment]
In my case stay works pro evolution soccer 3 - 4 and 5 (6 is cited before)

![pes3](https://user-images.githubusercontent.com/6601480/222992383-a33f4b29-945e-4a80-8c7e-368841ddb3e3.png)

![pes4](https://user-images.githubusercontent.com/6601480/222992396-494cb063-8277-4c9f-ab50-9cf519fd859f.png)

![pes5](https://user-images.githubusercontent.com/6601480/222992601-c8683ab8-4bf8-475e-ad27-e004bf22b532.png)

However in pro evolution 4 and 5 appear sound issues maybe wine issue

**Comment by mrdeathjr28** [comment]
Jaws working here too

![tbrn](https://user-images.githubusercontent.com/6601480/222992747-e9461055-77af-4bcd-8a74-898846b5856b.png)

**Comment by mrdeathjr28** [comment]
Test Drive 7 Works here too

![td7](https://user-images.githubusercontent.com/6601480/222992980-c71ab833-b809-4dfd-9dea-f4aa664174d8.png)

**Comment by mrdeathjr28** [comment]
Obscure

![obscr1](https://user-images.githubusercontent.com/6601480/222993073-48abe0c5-47c0-4a8c-87c8-2b5e469e1b68.png)

**Comment by mrdeathjr28** [comment]
World Racing

![mbwr](https://user-images.githubusercontent.com/6601480/222993176-84574aac-2077-4feb-9db5-c715fcd99b45.png)

Gameplay Video

https://www.youtube.com/watch?v=Rr151QOl96I

**Comment by mrdeathjr28** [comment]
Meet Robinsons

![mtrns](https://user-images.githubusercontent.com/6601480/222993209-4b52c9c4-3245-474b-a0f0-49eee5a04c2b.png)

Gameplay Video

https://www.youtube.com/watch?v=VEAOXkmuVkQ

**Comment by mrdeathjr28** [comment]
Chicken Little

![cklt](https://user-images.githubusercontent.com/6601480/222993269-5d7dc511-f999-4854-b890-aad4e02f003d.png)

Gameplay Video

https://www.youtube.com/watch?v=5JP7rH4ck8U

**Comment by mrdeathjr28** [comment]
Lord of the Rings Return of the King

![esdlarotk](https://user-images.githubusercontent.com/6601480/222993382-0dbb9301-769a-4187-b8ac-5bf70244bec5.jpg)

Gameplay Video

https://www.youtube.com/watch?v=3UWFipR4H68

**Comment by mrdeathjr28** [comment]
Virtua Tennis

![vttns](https://user-images.githubusercontent.com/6601480/222993623-96463bd9-7d64-4465-b984-dbd0a2bf47e4.jpg)

Gameplay Video

https://www.youtube.com/watch?v=nMNdKr6pREM

**Comment by mrdeathjr28** [comment]
007 Nightfire

![007nfr](https://user-images.githubusercontent.com/6601480/222993652-cbe36070-db0e-4a74-9542-c89b17456d15.jpg)

Gameplay Video

https://www.youtube.com/watch?v=IAc3oErDmA0

**Comment by mrdeathjr28** [comment]
Silent Hill 2

![slhl2](https://user-images.githubusercontent.com/6601480/222993791-f5567e59-883a-4192-a34b-6c255630a395.png)


Silent Hill 3

![slhl3a](https://user-images.githubusercontent.com/6601480/222993806-e1082ffc-f876-4c6a-bcee-b02fcf607899.png)

**Comment by mrdeathjr28** [comment]
Batman Revengeance but dont recognize input in language screen before main menu

![btrvg](https://user-images.githubusercontent.com/6601480/222994059-281f74aa-3312-41bd-b3c7-11075870a696.png)

Starsky and Hutch but crash at begin mission with pure error 6025 maybe c++ wine libraries

![stht](https://user-images.githubusercontent.com/6601480/222994066-292f909d-aa4e-4ecc-ac09-ecb988913435.png)

**Comment by mrdeathjr28** [comment]
V-Rally 3 but need disable cinematics because with them game crash

![vrll3](https://user-images.githubusercontent.com/6601480/222994218-9c36114f-b7cb-403a-b56a-29cd856f976a.png)

**Comment by mrdeathjr28** [comment]
Billy Hatcher but have sound problems

![blhtc](https://user-images.githubusercontent.com/6601480/222994679-d14f3e41-af09-4c28-8ab1-98be78ebe3f8.png)

**Comment by mrdeathjr28** [comment]
RallySportChallenge

![rlsch](https://user-images.githubusercontent.com/6601480/222996309-c09148f6-d1bf-4603-8225-d6ceb4353121.png)

**Comment by mrdeathjr28** [comment]
X-Men Legends 2

![xmnlg2](https://user-images.githubusercontent.com/6601480/222996495-5714cea0-1a0a-4abc-9ad0-f2e3d3981f9b.png)

**Comment by mrdeathjr28** [comment]
Harry Potter Quiddich World Cup

![hpqwc](https://user-images.githubusercontent.com/6601480/222996627-3d711093-ec17-43b9-8751-28ec1a282d19.png)

**Comment by mrdeathjr28** [comment]
Harry Potter and Azkaban Prisioner

![hp3](https://user-images.githubusercontent.com/6601480/222996783-a587ed1d-a42d-451d-8963-0ceb1f20a45a.png)

**Comment by mrdeathjr28** [comment]
Chrome

![chrm](https://user-images.githubusercontent.com/6601480/222996839-0231949f-2ed7-415f-9ea3-23b5486ad5c5.jpg)

**Comment by mrdeathjr28** [comment]
Shrek 2

![shrk2](https://user-images.githubusercontent.com/6601480/222997109-7247e162-967e-4f49-8f96-898465aecfae.png)

**Comment by mrdeathjr28** [comment]
Shrek Super Slam

![shrkss](https://user-images.githubusercontent.com/6601480/222997274-93a3b394-0121-4add-8173-8dbcd1442fcf.png)

**Comment by mrdeathjr28** [comment]
Simpsons Hit and Run

![smphar](https://user-images.githubusercontent.com/6601480/222997442-20c4704b-009f-44b0-affc-7e4dbc9832df.png)

**Comment by mrdeathjr28** [comment]
Aquanox

![aqnx1](https://user-images.githubusercontent.com/6601480/222997628-2503b253-8090-4d00-bd83-d4504759b052.png)

**Comment by mrdeathjr28** [comment]
Legacy of Kain Blood Omen 2

![lokbo2](https://user-images.githubusercontent.com/6601480/222998113-a1719ba2-df5c-44ce-9850-c0f8f50b6569.png)

Legacy of Kain Soul Reaver 2

![loksr2](https://user-images.githubusercontent.com/6601480/222998129-b97693e3-782c-4854-affe-7b27f77b8acb.png)

**Comment by mrdeathjr28** [comment]
Knights of Temple Infernal Crusade

![kotic](https://user-images.githubusercontent.com/6601480/222998299-16836ac8-90f5-4076-9980-32153ae6a91f.png)

**Comment by mrdeathjr28** [comment]
Sonic Heroes works but too slow in my case maybe related with audio issue

**Comment by mrdeathjr28** [comment]
Evil Dead Regeneration (Launcher dont work but game executable directly yes)

![evdrgn](https://user-images.githubusercontent.com/6601480/222999039-a0e03c56-d3d5-460e-a0f1-dd3651cee3df.png)

**Comment by mrdeathjr28** [comment]
Evil Dead Hail to King but dont leave more resolution than 640x480

![endhtk](https://user-images.githubusercontent.com/6601480/223002895-cb52bfb4-305f-4e73-8f40-b3bec258bd94.png)

**Comment by mrdeathjr28** [comment]
Daemon Vector

![damvctr](https://user-images.githubusercontent.com/6601480/223003675-e7691138-d0c6-4313-a8ee-e1da4b3f9ccf.png)

**Comment by mrdeathjr28** [comment]
Outlaw Golf have troubles with audio (rename audio carpet solve especially .sgt files need put in other folder (.dls audio files work ok)  and curiously dont shutdown all audio)

and with wine implementation have many stutter and with d8vk are smooth

![otlglwc](https://user-images.githubusercontent.com/6601480/223004420-493725f1-490c-4ee5-9e32-e2b61541477f.png)

**Comment by mrdeathjr28** [comment]
Chaos Legion try run but crash with this error

![chlg](https://user-images.githubusercontent.com/6601480/223005186-f6b6bb46-6838-483f-8f03-811b418172a4.png)

**Comment by mrdeathjr28** [comment]
The House of the Dead 3 works but entry on main game is very slow

![thod3](https://user-images.githubusercontent.com/6601480/223006404-7ed33b59-4898-4333-b1d8-d44649825d10.png)

however now in game with last d8vk runs more smooth in game

![thod3a](https://user-images.githubusercontent.com/6601480/223006640-b747904f-cee4-48e3-94d1-94653c079a21.png)

**Comment by mrdeathjr28** [comment]
Unreal 2 The Awakening works ok but .con audio files need be moved to other folder

![unr2ta](https://user-images.githubusercontent.com/6601480/223008089-1c37366c-b14a-4353-a456-d86dee473a29.png)

**Comment by mrdeathjr28** [comment]
Terminator 3 Rise of The Machines

![tm3rom](https://user-images.githubusercontent.com/6601480/223008286-22aa4935-43d7-466c-b6bc-9878955ed06c.png)

**Comment by mrdeathjr28** [comment]
XIII works ok

![xiii](https://user-images.githubusercontent.com/6601480/223008906-f9d83ee8-e7a0-4eba-9afe-cea94cba54d5.png)

**Comment by mrdeathjr28** [comment]
Alexander The Great

![alxtga](https://user-images.githubusercontent.com/6601480/223009446-d48ec0b2-e3b3-4db4-9b3b-7ed305569ad6.png)

![alxtgb](https://user-images.githubusercontent.com/6601480/223009456-92b642b3-eeb2-4ed3-aa8a-b66d804cbc54.png)

**Comment by mrdeathjr28** [comment]
Empire Earth 2

![eme2a](https://user-images.githubusercontent.com/6601480/223010375-bd286966-7a45-47a1-8d30-c94f46879a7e.png)

![eme2b](https://user-images.githubusercontent.com/6601480/223010393-ebc4f384-27f5-4769-b78c-50a610261608.png)

![eme2c](https://user-images.githubusercontent.com/6601480/223010410-8c26af4d-d894-49e4-856b-a85acb7ebd95.png)

**Comment by mrdeathjr28** [comment]
Max Payne

![mxpn1](https://user-images.githubusercontent.com/6601480/223011743-b7fa2daa-4765-417e-abd2-6a6ee8ecaff7.png)

Max Payne 2

![d8vkgit](https://user-images.githubusercontent.com/6601480/223011428-5b7e9065-d7c4-47bf-a864-3a056dc4a0e8.png)

**Comment by mrdeathjr28** [comment]
Marc Ecko's Getting Up crash at begins

![mceck](https://user-images.githubusercontent.com/6601480/223013246-439144df-9510-47b0-b9e3-b53cb43067da.png)

**Comment by mrdeathjr28** [comment]
Singles works in main menu but when try enter in main game crash

![sngla](https://user-images.githubusercontent.com/6601480/223014204-a523ff7e-aabc-4d3e-8f6d-052699832bf7.png)

**Comment by mrdeathjr28** [comment]
Shadows of Destiny  try begin but crash

**Comment by WinterSnowfall** [comment]
@mrdeathjr28 Thank you for all the reports! Note however that some of these game were already known to be compatible, so do check [the Wiki list](https://github.com/AlpyneDreams/d8vk/wiki) before posting anything on this thread to make sure you're not reconfirming something that's already been looked at. It's fine if you want to retest them, of course, to check for any problems we might have missed.

For any game where you encounter issues that are related to d8vk, namely graphical artifacts or crashes that do not happen on Windows or with WineD3D, we'd appreciate it if you could please open a separate issue for each of them, capture traces and fill out the issue template. Someone will then look into them. This thread is only for reporting and keeping track of games which are known to work and are not yet listed on the Wiki.

**Comment by mrdeathjr28** [comment]
True Crime Streets of LA

![tcsla](https://user-images.githubusercontent.com/6601480/223233163-32aedaed-3c2a-400e-a5d2-983df9eaa2c8.png)

![tcslaa](https://user-images.githubusercontent.com/6601480/223233190-d823b5f2-3948-4eff-9f6f-433fbf396280.png)

True Crime New York

![tcnyc](https://user-images.githubusercontent.com/6601480/223233263-cc8a4e0d-d026-4de2-b917-fe1ad7c1fe5f.png)

**Comment by mrdeathjr28** [comment]
The Hulk 2002

![thlka](https://user-images.githubusercontent.com/6601480/223233430-f5e8650a-9212-4e8d-92bd-740a2466e622.png)

![thlkb](https://user-images.githubusercontent.com/6601480/223233474-f0a75c57-7055-4a93-958f-1a7cf910cf4a.png)

**Comment by mrdeathjr28** [comment]
Magadascar

![mgdscr1](https://user-images.githubusercontent.com/6601480/223233576-1b98dca6-52f1-4a2a-9b63-03c19e5561b8.png)

**Comment by mrdeathjr28** [comment]
The Punisher

![tpna](https://user-images.githubusercontent.com/6601480/223233665-c29baf7f-86be-467e-bb2d-30b04225dad2.png)

![tpnb](https://user-images.githubusercontent.com/6601480/223233689-c3960896-8546-4502-af06-81babb159b58.png)

X-Men 2 Wolverine Revenge

![xm2wa](https://user-images.githubusercontent.com/6601480/223233797-bb53935f-1571-4338-88f6-6fc5b2736b8e.png)

![xm2wb](https://user-images.githubusercontent.com/6601480/223233843-0c3ab065-e21a-468d-b069-2a39b9dddc5c.png)

**Comment by mrdeathjr28** [comment]
Pro Race Driver

![prrcd1a](https://user-images.githubusercontent.com/6601480/223233971-81d7d8a5-bb05-4b64-b8b2-a1374a62b81f.png)

![prrcd1b](https://user-images.githubusercontent.com/6601480/223233994-e8a1de49-336d-43cf-aadf-dec17eaf2f18.png)

**Comment by Blisto91** [comment]
@mrdeathjr28 Very cool you are testing all these games thx! :grin: In the future it might make an easier overview if you could put screenshots behind a collapsible section.

**Comment by mrdeathjr28** [comment]
Tony Hawk Pro Skater 3 + Level Mod Full (cinematics folder need be renamed because with them game crash)

![thps3mdsa](https://user-images.githubusercontent.com/6601480/223252318-147ef4b3-48e9-4fe3-ab50-4668b3f68f4b.png)

Tony Hawk Pro Skater 4

![proskt4](https://user-images.githubusercontent.com/6601480/223251976-5e00edd8-9f77-4f75-adea-1a8b71bc8a8f.png)

**Comment by mrdeathjr28** [comment]
Kelly Slater Pro Surfer: game shows texture flickering but dont possible play because dont recognize keyboard

![kspsa](https://user-images.githubusercontent.com/6601480/223268229-91a2c1ea-b778-45b2-b265-f3790059b456.png)

![ksps](https://user-images.githubusercontent.com/6601480/223268284-d6b97e0a-70e8-4571-98e8-bbda76492900.png)

**Comment by mrdeathjr28** [comment]
Advent Rising

![adrsa](https://user-images.githubusercontent.com/6601480/223305296-eada45b6-c3d0-45fd-b555-4879a041b0d2.png)

![adrsb](https://user-images.githubusercontent.com/6601480/223305313-00e0fe97-6dbd-41a1-b4a0-76cc989ce2be.png)

Shark Tale

![esta](https://user-images.githubusercontent.com/6601480/223305349-2cf73aeb-0f83-4021-b1d8-3ee0aef11ffa.png)

![estb](https://user-images.githubusercontent.com/6601480/223305365-d3e3bc18-b2c4-4d81-b1fa-62412844b82c.png)

The Hobbit

![hbta](https://user-images.githubusercontent.com/6601480/223305414-e01f18b7-1e52-4794-be34-4073d75ebe2c.png)

![hbtb](https://user-images.githubusercontent.com/6601480/223305437-b57b5854-ed21-41e6-ad62-ab438fecf715.png)

**Comment by mrdeathjr28** [comment]
Paris Dakar works but still selected more screen resolution stay on lower resolution and need dinput8 as native for input

![prdkr](https://user-images.githubusercontent.com/6601480/223305756-206e8381-d287-4557-8872-df3fef5e92e3.png)

In other titles case fellowship of lord of the rings can select settings but crash when try run game

**Comment by Blisto91** [comment]
@mrdeathjr28 Please see comment above https://github.com/AlpyneDreams/d8vk/issues/75#issuecomment-1457043796

**Comment by mrdeathjr28** [comment]
4x4 Evo and 4x4 Evo 2 only show configuration screen and freeze in my case

**Comment by Blisto91** [comment]
> 4x4 Evo and 4x4 Evo 2 only show configuration screen and freeze in my case

Make a new issue for any games you find that doesn't work. Be sure to check there isn't already a issue first.

**Comment by mrdeathjr28** [comment]
> > 4x4 Evo and 4x4 Evo 2 only show configuration screen and freeze in my case
> 
> Make a new issue for any games you find that doesn't work. Be sure to check there isn't already a issue first.

I wait for fix bloodrayne issues maybe when this issue are fixed can affect 4x4 evo and 4x4 evo 2 because both games are from terminal reality

**Comment by RyuSeisuke1992** [comment]
Has anyone tested this method with ObsCure? ObsCure Steam version is based on Direct8 and does not launch for Linux/Steam deck
https://github.com/ValveSoftware/Proton/issues/2633

**Comment by mrdeathjr28** [comment]
> Has anyone tested this method with ObsCure? ObsCure Steam version is based on Direct8 and does not launch for Linux/Steam deck [ValveSoftware/Proton#2633](https://github.com/ValveSoftware/Proton/issues/2633)

Yeah in upper part i upload image with obscure GOG and runs ok, this images are in game

![obc1a](https://user-images.githubusercontent.com/6601480/227394730-08c1d336-a1ff-4a3c-a429-a957a9485862.png)

![obc1b](https://user-images.githubusercontent.com/6601480/227394825-579ea083-ea8d-4164-8e73-7f92de390ae8.png)

And runs other titles like the thing normal and with mods

![thgbf](https://user-images.githubusercontent.com/6601480/227395855-8282a106-6821-45f8-80f0-fdd99155c7b9.png)

![tngmd1](https://user-images.githubusercontent.com/6601480/227395434-652e11a0-b132-442f-8b36-bc19ebcb446a.png)

![ttngmd2](https://user-images.githubusercontent.com/6601480/227395449-1bcd27cc-b86c-4f2d-8550-3fb9bb28390f.png)

Nascar Thunder 2003

![nc2k3](https://user-images.githubusercontent.com/6601480/227395540-6e4808ee-7986-42bf-8d30-a6c0145e3331.png)

**Comment by WinterSnowfall** [comment]
Summarizing mrdeathjr's very graphic feedback above, here are the list of games reported confirmed as working (which WEREN'T already listed on the wiki):
- Alexander The Great
- Billy Hatcher
- Chicken Little
- Chrome
- Daemon Vector
- Evil Dead: Regeneration
- Harry Potter and the Prisoner of Azkaban
- Harry Potter: Quidditch World Cup
- James Bond 007: Nightfire
- Jaws
- Knights of the Temple: Infernal Crusade
- Magadascar
- Meet the Robinsons
- Nascar Thunder 2003
- Obscure
- Outlaw Golf
- Pro Evolution Soccer 3, 4 & 5
- Pro Race Driver
- RalliSport Challenge
- Shark Tale
- Shrek SuperSlam
- Terminator 3: Rise of the Machines
- Test Drive 7
- The Hobbit
- The Hulk (2002)
- The Punisher
- The Simpsons: Hit & Run
- The Thing
- True Crime: New York City
- True Crime: Streets of LA
- Virtua Tennis
- V-Rally 3 
- World Racing
- X2: Wolverine's Revenge
- X-Men Legends II: Rise of Apocalypse

May need further testing, no in game confirmation yet:
- Batman: Vengeance
- Sonic Heroes
- Starsky & Hutch

Have d3d8 related issues/crashes and may need to be looked into:
- 4x4 Evo
- 4x4 Evo 2
- Chaos Legion
- Evil Dead: Hail to the King
- Kelly Slater's Pro Surfer
- Marc Eckō's Getting Up: Contents Under Pressure
- Paris-Dakar Rally
- Shadow of Memories
- Singles: Flirt Up Your Life
- The House of the Dead III

We'd appreciate this kind of testing & feedback in the future. Screenshots don't help anyone unless you use them in issues to describe certain problems. Please refrain from clogging up this thread with images otherwise. Thank you!

**Comment by mrdeathjr28** [comment]
Thanks to WinterSnowfall for this https://github.com/AlpyneDreams/d8vk/pull/122 various games are fixed like:

Bloodrayne 1 

![br1a](https://user-images.githubusercontent.com/6601480/227554433-af411a29-9688-409c-96e4-66d761978685.png)

![br1b](https://user-images.githubusercontent.com/6601480/227554456-63bcf42f-5a1c-4bc4-809a-83e9ce8f21de.png)


Bloodrayne 2

![br2a](https://user-images.githubusercontent.com/6601480/227554298-c329dcef-3ab3-4e1b-8155-d77b7b9e87a3.png)

![br2d](https://user-images.githubusercontent.com/6601480/227554364-911c53a2-e536-433f-8c64-07774bf617f3.png)


Bloodrayne 1 Terminal Cut

![brtcb](https://user-images.githubusercontent.com/6601480/227554181-f6c7580f-9a71-4e9f-b6bf-318ca06caeb8.png)

![brtcc](https://user-images.githubusercontent.com/6601480/227554216-e8aaa625-ce0c-4393-b3c5-10fc5e90a061.png)


4x4 Evolution 2

![4x42b](https://user-images.githubusercontent.com/6601480/227554087-84da7922-a596-48a1-855b-6b906c29045e.png)

![4x42c](https://user-images.githubusercontent.com/6601480/227554809-11dcb731-b1a0-49d3-8ed8-d95ccc866df9.png)

**Comment by RyuSeisuke1992** [comment]
> > Has anyone tested this method with ObsCure? ObsCure Steam version is based on Direct8 and does not launch for Linux/Steam deck [ValveSoftware/Proton#2633](https://github.com/ValveSoftware/Proton/issues/2633)
> 
> Yeah in upper part i upload image with obscure GOG and runs ok, this images are in game
> 
> ![obc1a](https://user-images.githubusercontent.com/6601480/227394730-08c1d336-a1ff-4a3c-a429-a957a9485862.png)
> 
> ![obc1b](https://user-images.githubusercontent.com/6601480/227394825-579ea083-ea8d-4164-8e73-7f92de390ae8.png)
> 
> And runs other titles like the thing normal and with mods

Thanks but unfortunately this is the GOG version. I would have been interested if the Steam version also works. :/

**Comment by AlpyneDreams** [comment]
> Jaws working here too
> 
> [tbrn](https://user-images.githubusercontent.com/6601480/222992747-e9461055-77af-4bcd-8a74-898846b5856b.png)

What Jaws game is this?

**Comment by AlpyneDreams** [comment]
> Chaos Legion try run but crash with this error
> 
> [chlg](https://user-images.githubusercontent.com/6601480/223005186-f6b6bb46-6838-483f-8f03-811b418172a4.png)

Does this still happen?

**Comment by AlpyneDreams** [comment]
We are no longer accepting new games that work. After the next release, it will be assumed all games work unless an issue is opened for them. Thank you to everyone who was active in this thread.

**Comment by mrdeathjr28** [comment]
> > Jaws working here too
> > [tbrn](https://user-images.githubusercontent.com/6601480/222992747-e9461055-77af-4bcd-8a74-898846b5856b.png)
> 
> What Jaws game is this?

Majesco title about jaws movie

**Comment by mrdeathjr28** [comment]
> > Chaos Legion try run but crash with this error
> > [chlg](https://user-images.githubusercontent.com/6601480/223005186-f6b6bb46-6838-483f-8f03-811b418172a4.png)
> 
> Does this still happen?

Now dont crash but stay in black screen

**Comment by AlpyneDreams** [comment]
Also, if you'd still like to report games that are broken without creating a new issue in the future you can go to #147.

**Comment by AlpyneDreams** [comment]
> Majesco title about jaws movie

> Now dont crash but stay in black screen

I see, thanks.
