### ISSUE TITLE
Duke Nukem - Manhattan Project crashes on startup

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#79]
It also crashes when attempting to trace, which is unfortunate.

The game has both D3D8 and OpenGL renderers, but looks to be rather janky with D3D8 and:
- ~~crashes outright on ANV~~ - nevermind, it also works on ANV with WineD3D, I just had to pull latest mesa
- works on Nvidia with WineD3D, but complains about being unable to present and crashes on alt+tab (and sometimes on startup, if you unfocus its main window)

It does appear to render everything corrently otherwise with WineD3D. 

Using d8vk makes it crash on startup with an ACCESS_VIOLATION exception according to the game's own logs: [prism3d.crash.log](https://github.com/AlpyneDreams/d8vk/files/10383141/prism3d.crash.log)

### Software information
Duke Nukem - Manhattan Project (GOG version, sadly no longer sold)

### System information
- GPU: RTX 3060
- Driver: 525.60.11
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
None - the game crashes on trace as well...

### Log files
- d3d8.log: [prism3d_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10383159/prism3d_d3d8.log)
- d3d9.log: [prism3d_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10383162/prism3d_d3d9.log)

**Comment by AlpyneDreams** [comment]
@WinterSnowfall Can you confirm that merging #91 fixed this?

**Comment by WinterSnowfall** [comment]
Looks good on latest master, yes :+1: 

![DNMP](https://user-images.githubusercontent.com/6306593/216088604-747934d2-1713-4aea-ab8d-bf91437c039a.png)
