### ISSUE TITLE
"Rough" framerate (~0.5 fps) during gameplay in Warrior Kings (- Battles)

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#80]
The games (there are 2 in the series, built on the same engine) are most likely doing something stupid, since even WineD3D chugs at below 20fps during gameplay, but d8vk can't even hold 1 fps for some reason :/...

The good news is that everything looks entirely correct, although the games are unplayable slideshows.

### Software information
Warrior Kings / Warrior Kings - Battles (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
[warrior_kings.trace.tar.xz](https://drive.google.com/file/d/1ZTD4uptmC2z-DWQFWRGPtOOa5B4SBIc2/view?usp=share_link)

### Log files
- d3d8.log: [warrior_kings_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10420532/warrior_kings_d3d8.log)
- d3d9.log: [warrior_kings_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10420533/warrior_kings_d3d9.log)

**Comment by dungeon007** [comment]
That is using SWVPs, which are known to be utter slow on DXVK D3D9.
Try it on DGVoodoo2 or Gallium NINE (via d3d8to9) these have them not slow, unlike WINED3D and particulary DXVK D3D9.

**Comment by WinterSnowfall** [comment]
I'm not sure what problems with SWVP you're referring to, because we have come across other games that use it and don't exhibit any noticeable performance problems with d8vk/dxvk, nor WineD3D for that matter.

I have tried running the game with dgVoodoo 2 + dxvk, however that crashes the game on mission start.

The good news is that I've also retested the game with d8vk, on both Nvidia and ANV and the problem I had originally described is gone. The game still doesn't perform exceptionally well when zoomed out (it's still above 30fps on an Intel Xe-LP iGPU), but it's certainly comparable to WineD3D now, if not a bit better, not a slideshow.

**Comment by dungeon007** [comment]
Being a bit better than WINED3D in this case isnt plausable. It should be like 3x faster than that.
"dgVoodoo 2 + dxvk, however that crashes the game on mission start."
OK, i was testing on RADV and AMD APU. Maybe that is better working with dgVoodoo2 than else.
