### ISSUE TITLE
Missing textures in Rayman 3

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#81]
Some objects are untextured or textured incorrectly. It doesn't appear to be caused by CopyRects missing transfers from DEFAULT to MANAGED in this case.

WineD3D also doesn't render things correctly, but it does appear to get some textures right. I'll have to try it on Nvidia to see if ANV isn't at fault here.

I've tried to capture a trace but it crashed before reaching the main menu. Doesn't appear to be entirely empty however, so hopefully it does contain something relevant.

### Software information
Rayman 3 (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
[Rayman3.trace.tar.xz](https://drive.google.com/file/d/1Kavv_TBWQeu4zlq_57TY8esENjV1EMia/view?usp=share_link)

### Log files
- d3d8.log: [Rayman3_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10420616/Rayman3_d3d8.log)
- d3d9.log: [Rayman3_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10420618/Rayman3_d3d9.log)

**Comment by WinterSnowfall** [comment]
P.S.: Gave it a go on Nvidia, and can confirm it's not an ANV problem. Same missing textures/see-through surfaces show up here as well, including with WineD3D.

**Comment by mrdeathjr28** [comment]
Yeah here shows similar error with UHD 630 GT2

![rmn3d8vk](https://user-images.githubusercontent.com/6601480/213291965-43a2afd1-0baf-4b6f-8bee-3be88a07b1b7.jpg)

**Comment by WinterSnowfall** [comment]
Apparently the missing textures are a known problem with the game and there is an unofficial mod that fixes it: https://raymanpc.com/forum/viewtopic.php?f=13&t=12854

The mod ships its own d3d8.dll - not sure what that does, but it does look like it brings back some of the textures (some character textures still look wrong with d8vk though).

I'll attempt to grab a trace with the mod applied, perhaps that will shed some light into what's going on.

**Comment by WinterSnowfall** [comment]
The good news is that I got a d3d9 trace of the mod by using d3d8to9 + d8vk: [Rayman3.mod.trace.tar.xz](https://drive.google.com/file/d/15PEXv-YZOajmJAaoUsK3gTtypdYORAtt/view?usp=share_link)

The bad news is that the mod absolutely kills performance to a level that the game simply becomes unplayable in WineD3D. I'm not entirely sure why, but it seems to force CS syncs in certain places.

By the looks of it though, and considering that WineD3D is also broken without the mod, the game is clearly doing something wrong and will need some sort of workaround to render everything correctly. Might be a tough one to fix.

**Comment by WinterSnowfall** [comment]
I've looked into this a bit more closely, and it seems like Rayman 3 with Better Rayman works well with d8vk already. 

![Rayman3](https://user-images.githubusercontent.com/6306593/227740050-b2aeb408-ba9e-4969-8472-c0a8ab8dfec2.png)

I don't think we should spend more time backporting whatever Better Rayman is doing, since the original version of the game most likely relied on some driver hacks to render properly. WineD3D also needs Better Rayman to render correctly, and according to some posts I've read so do some native drivers.

**Comment by mrdeathjr28** [comment]
No sadly in my case with intel graphics still have troubles

![rymn3b](https://user-images.githubusercontent.com/6601480/227776260-f02ab9e8-32f9-4516-8923-7e4b48ef0f93.png)

[Rayman3_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11071598/Rayman3_d3d8.log)

Sadly dont leave make a trace, crash loading main menu

**Comment by WinterSnowfall** [comment]
It works on Intel as well, I have checked, but you need both d3d8.dlls. To be more exact:
- the d3d8.dll from Better Rayman next to the game exe
- the d8vk d3d8.dll in system32/syswow64, where it is normally installed in Wine
- a Wine override for d3d8.dll with "n,b"

**Comment by mrdeathjr28** [comment]
No in my case stay without change

![rmn3goga](https://user-images.githubusercontent.com/6601480/227782293-c3a7fb85-dc52-40a5-9e11-83e7b67fa87a.png)

Maybe can stay related to mesa drivers if you have xe igp based is diferent compared igp before xe

Curiously with d3d8to9 graphics are ok

![d3d8to9](https://user-images.githubusercontent.com/6601480/227782544-0c777627-52b9-4ff8-a877-d141c245a402.png)

**Comment by WinterSnowfall** [comment]
Here is my d3d8.ini config file. I have not changed anything in the game folder outside of installing the game (GOG version) and then the [Better Rayman 3](https://raymanpc.com/forum/viewtopic.php?p=992390&sid=a7a0f8f8607aa1ec50bf95b0c6d59919#p992390) mod. If you are using the same with latest d8vk (from main branch) there's no reason for it not to work outside of it being misconfigured:

```
;; Config file for DirectX DLL Wrapper
[General]
LoadCustomDllPath        = BetterRayman3.dll

[Compatibility]
D3d8to9                  = 0
DdrawCompat              = 0
ForceTermination         = 0
SingleProcAffinity       = 0

[Window]
FullScreen               = 0
WaitForWindowChanges     = 0
```

**Comment by mrdeathjr28** [comment]
> Here is my d3d8.ini config file. I have not changed anything in the game folder outside of installing the game (GOG version) and then the [Better Rayman 3](https://raymanpc.com/forum/viewtopic.php?p=992390&sid=a7a0f8f8607aa1ec50bf95b0c6d59919#p992390) mod. If you are using the same with latest d8vk (from main branch) there's no reason for it not to work outside of it being misconfigured:
> 
> ```
> ;; Config file for DirectX DLL Wrapper
> [General]
> LoadCustomDllPath        = BetterRayman3.dll
> 
> [Compatibility]
> D3d8to9                  = 0
> DdrawCompat              = 0
> ForceTermination         = 0
> SingleProcAffinity       = 0
> 
> [Window]
> FullScreen               = 0
> WaitForWindowChanges     = 0
> ```

In my case appear same, however for now with d3d8to9 work

**Comment by WinterSnowfall** [comment]
I've had the chance to run the game on Windows XP and a GeForce 4, and indeed, on age-accurate hardware and drivers, it renders the textures just fine, without the need of unofficial patches. 

It would be nice if we could figure out why that is happening and have a workaround for it (even if it relies on some sort of incorrect behavior that was in drivers at the time). I'll reopen the issue and potentially look into it at some point.

**Comment by mrdeathjr28** [comment]
> I've had the chance to run the game on Windows XP and a GeForce 4, and indeed, on age-accurate hardware and drivers, it renders the textures just fine, without the need of unofficial patches.
> 
> It would be nice if we could figure out why that is happening and have a workaround for it (even if it relies on some sort of incorrect behavior that was in drivers at the time). I'll reopen the issue and potentially look into it at some point.

I test again maybe when appear dxvk 2.4, maybe d8vk stay merged for release

**Comment by WinterSnowfall** [comment]
Seems like Better Rayman is either using d3d8to9 or dxwrapper to apply this fix: https://github.com/crosire/d3d8to9/blob/2b25f270c4119437e80e52f41d0dc30236c62865/source/d3d8to9_vertex_buffer.cpp#L88

If I replicate this behavior, it does indeed seem to fix the issue, so I am guessing this is also inline with what native was doing, at least in the Windows XP era, because the game doesn't run into this issue on an age-accurate system.

**Comment by dungeon007** [comment]
For a BetterRayman3, it is probably better to use files from ray3fix https://gamebanana.com/mods/492495 
This avoids dxwrapper's d3d8 loading BR, here is **winmm.dll** as a loader to **scripts/BetterRayman3.asi** and dinput8, optionally probably you want dsound, maybe yes, maybe dont... and DGVoodoo2 files you can delete.
 In ubi,ini select a resolution you want, your desktop res i guess, etc...
As for a bug, seems like you can just add **d3d9.allowDiscard = False** as a workaround.
![R3](https://github.com/user-attachments/assets/d5a1a5ae-082e-48f1-8f8c-612635c11831)

**Comment by Blisto91** [comment]
`d3d9.allowDiscard` was removed in dxvk 2.3

**Comment by dungeon007** [comment]
Hm, then i have no idea how this started working... i played with older drivers a bit selected this... and somehow it started working even on more recent, weird... :D

**Comment by WinterSnowfall** [comment]
> As for a bug, seems like you can just add **d3d9.allowDiscard = False** as a workaround.

That option has been removed some time ago, just like Blisto mentioned. I've fixed the problem with: https://github.com/doitsujin/dxvk/pull/4143 , which won't penalize applications that don't depend on this d3d8 buffer discard quirk. And we haven't seen anything besides Rayman 3 abusing this behavior so far.

> It more seems to me, that order of loading of these wrappers was what corrupting something there... as BetterRayman3.asi or dll is identical :D

I have fixed the base game without any mods or patches. Should you use Better Rayman, it will apply this fix for you anyway.

**Comment by dungeon007** [comment]
>I have fixed the base game without any mods or patches.
For which base version? 1.0, 1.0.2, GoGs, retail anniversary... i heard that there are many versions differences :D
Who will play original version when it fluctuates FPS in half all the time? 
If not synced and your screen is at 60Hz, then game runs at 72 fps. Further if yours screen is at 75Hz then game runs at 90 fps, etc... and then goes in half to 36 or 45, etc... because of this you want to mod it anyway, regardless if you want to run wide or original 4:3.

**Comment by WinterSnowfall** [comment]
> For which base version? 1.0, 1.0.2, GoGs, retail anniversary... 

Whatever GOG has. But I think it would fix original retail copies also.

> Who will play original version when it fluctuates FPS in half all the time?

Disabling direct buffer mapping actually helps a lot in this regard (part of my PR). The game still drops to half the framerate at times, but a lot less frequently. It's the best I could do for people who may not be aware Better Rayman exists.

> If not synced and your screen is at 60Hz, then game runs at 72 fps. Further if yours screen is at 75Hz then game runs at 90 fps, etc...

No, that won't happen with dxvk's new vsync frame limiter. You can see in the logs that it's properly preventing the game from overshooting the refresh rate.

**Comment by dungeon007** [comment]
For now just to confirm, one needs 100Hz screen so that game run at 120 fps
![100Hz4120fps](https://github.com/user-attachments/assets/e4f6b7d8-3d26-4ebb-8d8f-98347894cb13)

**Comment by WinterSnowfall** [comment]
Fixed in dxvk master (or rather worked around, since the game's behavior is dependent on an odd implementation detail) by https://github.com/doitsujin/dxvk/pull/4143.
