### ISSUE TITLE
Xanadu Next needs more CopyRects

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#82]
`debug: CopyRects: Hit unhandled case from src pool 0 to dst pool 1`

I assume this is the missing DEFAULT to MANAGED?

Opening an issue only to keep track of it. I'd normally attach a trace, but I have to sit through 10 minutes of intro cutscenes and cinematics to get anything relevant, so... I'll only do it if I have to.

### Software information
Xanadu Next (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
N/A

### Log files
 -d3d8.log: [XANADU_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10420686/XANADU_d3d8.log)
-d3d9.log: [XANADU_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10420687/XANADU_d3d9.log)

**Comment by mrdeathjr28** [comment]
In my case with UHD-630 GT2 and d8vk

![xnnd8vk](https://user-images.githubusercontent.com/6601480/213303347-97d56bcc-58bf-4df5-a455-064fab5b1c5f.jpg)

and with d3d8to9 + d9vk

![xnnd3d8to9d9vk](https://user-images.githubusercontent.com/6601480/213303485-aa50c2af-f53d-4350-81be-26efc8af672e.jpg)

**Comment by WinterSnowfall** [comment]
The game looks fine now, even on main.

![XNMain](https://user-images.githubusercontent.com/6306593/229477099-1ffc4398-fe60-47e6-b23b-aaf992948ec7.png)

However, I'll keep the issue open until DEFAULT->MANAGED is implemented, as the game is apparently using it (although I'm not sure if anything actually depends on it).

**Comment by AlpyneDreams** [comment]
I'm gonna close this since the game works and we can track DEFAULT->MANAGED in #116

**Comment by mrdeathjr28** [comment]
Yeah works ok in my case with lastest d8vk

![xnnxt](https://github.com/AlpyneDreams/d8vk/assets/6601480/023f8f40-60dc-4966-b1c1-ed154e743352)
