### ISSUE TITLE
Nosferatu - Wrath Of Malachi crashes on startup

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#87]
The game outright crashes with the following error message:

![Error](https://user-images.githubusercontent.com/6306593/212757481-0ebe207b-d3d8-43f3-9461-6e076f943b24.png)

It works fine with WineD3D, but during gameplay it drops to an astounding 3 fps... unless the game is doing some form of ray tracing in d3d8 (supposedly it's built using a "Architectural Generator Engine"), I'm not sure what's going on. It's unplayable in its current state, so maybe something d8vk can help "resurrect".

The attached trace plays back fine and doesn't reproduce the crash, sadly.

### Software information
Nosferatu - Wrath Of Malachi (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/Mesa 23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
[Nosferatu.trace.tar.xz](https://drive.google.com/file/d/1bE08qVQ-wplvCicMEZeTmd69zpCQPK2_/view?usp=share_link)

### Log files
- d3d8.log: [Nosferatu_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10429154/Nosferatu_d3d8.log)
- d3d9.log: [Nosferatu_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10429156/Nosferatu_d3d9.log)

**Comment by WinterSnowfall** [comment]
So I've looked at this trace and the one for **Iron Storm** (#88) on Nvidia, and both actually crash on replay (gee, thanks ANV... ). The crashing happens in a call to **D3D8StateBlock::Capture()** for this issue and in a call to **D3D8StateBlock::Apply()** for #88, but I can't figure out what the problem is, unfortunately. I believe **m_stateBlock** gets corrupted somehow, or is not captured properly at times? Hope it will save you some time and give you a starting point at least.

**Comment by Blisto91** [comment]
Maybe one day I'll be able to add something intelligent to an issue also 🤔

**Comment by WinterSnowfall** [comment]
Nevermind the StateBlock things above, for some reason the apitrace version I had crashed on those, but they're not relevant.

![Nosferatu](https://user-images.githubusercontent.com/6306593/223129354-99113401-6d00-4987-a446-9f17335d7a8d.png)

The game will crash if **CheckDepthStencilMatch()** returns D3D_OK for **D3DFMT_D24X4S4**. WineD3D returns D3DERR_NOTAVAILABLE for it, and the game hapilly falls back to using **D3DFMT_D24X8**.

Mimicking this behavior in d8vk (forcing the game to pick **D3DFMT_D24X8**) gets it going, but I'm not sure why this is a problem in the first place or how to properly fix it. Should we just include a config option to disable this format in particular?
