### ISSUE TITLE
Massive Assault - broken rendering when shading is turned on

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#98]
This is how the main menu looks when the "Shading" option is turned on:
![MassiveAssault](https://user-images.githubusercontent.com/6306593/216434787-011e9ea0-55e1-4209-b90d-f9f33ec19328.png)

VS how it looks with shading turned off:
![MassiveAssaultNS](https://user-images.githubusercontent.com/6306593/216434994-20361ba4-2180-4ff1-ad0d-e33a9855d76d.png)

Both look fine with WineD3D. The trace I've captured (with "Shading" on) crashes on replay when it reaches the main menu, though the game itself doesn't crash at that point, but is as seen in the above screenshot.

### Software information
Massive Assault (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: f4988e7

### Apitrace file(s)
[ma.trace.tar.xz](https://drive.google.com/file/d/1XTgvArgC03yoCvDlD2BsIMQgf5g6f3ib/view?usp=share_link)

### Log files
- d3d8.log: [ma_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10572847/ma_d3d8.log)
- d3d9.log: [ma_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10572855/ma_d3d9.log)

**Comment by WinterSnowfall** [comment]
Trace playback crashes unless the surface is reffed in SetRenderTarget, namely uncommenting:
```
        // FIXME: Doing this crashes a GTA Vice City trace
        // and possibly other things too. Investigate.
        m_renderTarget = ref(surf);
```
Rendering is still wrong however even after this change, albeit a bit more correct, and there's a failed call to `IDirect3DDevice8::SetRenderState(this = 0xa9d068, State = D3DRS_SOFTWAREVERTEXPROCESSING, Value = TRUE)` which returns D3D_OK on WineD3D.

From what I can tell, it should only fail when `canSWVP()` returns false inside D3D9 code, but it's unclear to me why this happens with this game, since it seems to work just fine with other D3D8 titles.

![MAREF](https://user-images.githubusercontent.com/6306593/216833501-733b38c6-e86d-4fe2-8da8-947db9c48259.png)

**Comment by AlpyneDreams** [comment]
I'll look into the Vice City crash to see what's up with that so we can get that fixed at least.

**Comment by AlpyneDreams** [comment]
Good news! It was fixed yesterday!

**Comment by AlpyneDreams** [comment]
Looking into the swvp issue now.

**Comment by AlpyneDreams** [comment]
Looks like the game is creating a HAL device with `D3DCREATE_HARDWARE_VERTEXPROCESSING` and `D3DCREATE_PUREDEVICE`. Obviously you can't use SWVP in HWVP mode, so the application is being stupid here. I will make SetRenderState just return D3D_OK if we're not in mixed mode.

**Comment by AlpyneDreams** [comment]
Looking into that big blue square. Even if SWVP is forced on, that still happens.
